### ISSUE TITLE
[Bug]: Newly created pyiceberg table does not detect commit conflicts

### ISSUE THREAD

**Issue by HaraldVanWoerkom** [projectnessie/nessie#10062]
### What happened

Using pyiceberg and Nessie 0.99, I create a table.
Then I start multiple processes that write to that table in parallel. When these processes write at the same time, conflicts may occur, which is expected. However, for the first write, this conflict detection is not operational.
I asked about this with the pyiceberg people and they pointed me to the Nessie REST catalog implementation (see https://github.com/apache/iceberg-python/issues/1366). Apparently there is an interface misinterpretation:
- When a snapshot update is accompanied with an assert-ref-snapshot-id with an id set to None, this should be interpreted as "only do this commit if there is no snapshot", as is specified in the interface code documentation.
- However, it seems that Nessie skips this assert and also applies the change if a snapshot is available at the time of commit
- This overwrites the existing snapshot, thereby effectively deleting the existing information from the table

### How to reproduce it

1. Use pyiceberg and Nessie
2. Create a table
3. Launch 2 processes
4. Let those processes write a lot of data (several MB). Let them write in two batches. Let them retry on conflict (e.g. use tenacity)
5. After they are done check that all data from the two processes has been written
6. You will find that the second batch will always be written, but the first batch from one of the processes will often be dropped (if you write enough data this is >90% reproduceable)

### Nessie server type (docker/uber-jar/built from source) and version

build from source, 0.99.1

### Client type (Ex: UI/Spark/pynessie ...) and version

pyiceberg

**Comment by snazy** [comment]
Thanks for the bug report and analysis!

We'll publish a Nessie patch release with a fix shortly.

**Comment by HaraldVanWoerkom** [comment]
We ran the reproduction test on the latest code and we can confirm that this solves the issue. Thank you.
