### ISSUE TITLE
Update VersionStore to store a small value associated with each key

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#104]
There are multiple use cases where being able to filter by object key type is useful. For example, if I want to list all tables in Hive within a database that also contains Delta Lake tables, I should be able to filter that without having to read the current value for each key. My current thinking is this could be optimized by an extension whereby we save a 2 or 4 byte attribute along with each key and value. This would be used for storing things like object type to allow efficient getKeys() like operations for subsets of operations. The api changes would be independent of #81 but the efficient implementation would depend on that issue/change.

**Comment by rymurr** [comment]
closed with #781
