### ISSUE TITLE
Update VersionStore interface to support storing an extended object in addition to the base value

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#105]
Right now, serialized values are restricted to a relatively small size in DynamoVersionStore (or they should be). We need to enhance the store interface so we support an extended value that is stream based and can be read independently of the base value. This should provide a relatively clean interface working with larger objects.

**Comment by rymurr** [comment]
This is also known as offloading storage to the underlying blob store...to avoid storing HUGE objects in the Nessie DB

**Comment by snazy** [comment]
Superseded by #1638
