### ISSUE TITLE
Add unit/integration test for our demo Jupyter notebook

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1094]
We don't have any automatic tests for the Jupyter demo notebooks, but a) we use those quite often during presentation and b) need to manually verify those during every release. Accidental breaking changes in the code base and potentially libraries (Java, REST, Python, Iceberg, Spark, ...) can break those.

Maybe [Testbook](https://github.com/nteract/testbook) ([slides](https://docs.google.com/presentation/d/15MNTroTUDhprB3Y3CPtB-apiljb_y9FubwiijgLFGSQ/)) or [Papermill](https://github.com/nteract/papermill) could help.

**Comment by nastra** [comment]
We added our first test via `testbook` here: https://github.com/projectnessie/nessie-demos/blob/main/colab/tests/test_nessie_iceberg_demo_nba.py
