### ISSUE TITLE
why we can not find the file 'DelegatingHive3NessieRawStore.java'

### ISSUE THREAD

**Issue by OceanHu529** [projectnessie/nessie#1111]
I only find DelegatingHive3NessieRawStore.class in JAR. But it does not  appear in the branch main.

**Comment by snazy** [comment]
I assume you refer to the [table here](https://projectnessie.org/tools/hive/#setup).

All these classes are generated and basically just delegate to `org.projectnessie.hms.BaseRawStore`. The actual code generator is `org.projectnessie.hms.CodeGenerator` and invoked in the Maven pom.xml in the `nessie-hms-hive2` and `nessie-hms-hive3` modules.

You can see the source code for those by cloning the source code repo and running `./mvnw clean package -DskipTests`.

**Comment by snazy** [comment]
Note: please use either the Google Group or Slack mentioned in [here](https://github.com/projectnessie/nessie/blob/main/CONTRIBUTING.md) for general questions.
