### ISSUE TITLE
Schema migration tool

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1123]
Tool to be able to do the following:

* migrate version store schema when changed between versions
* import/export history from/to Nessie for backup and recovery

**Comment by snazy** [comment]
Nothing to migrate yet, so removing the 1.0.0 milestone

**Comment by rymurr** [comment]
Want to talk about it in the meeting so readding to milestone

**Comment by snazy** [comment]
Closing in favor of #4012
