### ISSUE TITLE
Iceberg Catalog Migration Tool

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1124]
A tool to migrate the owner of an Iceberg table from eg Hive to Nessie.

Also more generally migration strategy for using Nessie

**Comment by snazy** [comment]
Nothing to migrate yet, so removing the 1.0.0 milestone

**Comment by rymurr** [comment]
Want to talk about it so adding back to milestone

**Comment by ajantha-bhat** [comment]
The goal of this ticket (As per my assumption)

- Introduce a CLI tool (can stay in nessie-tools module) that can migrate (read as move, not copy) Iceberg tables in non-Nessie catalog to Nessie catalog. There are many catalogs that support iceberg tables(Hive, Hadoop, Glue, dynamodb, ECS, JDBC, REST). We should first focus on Hive, glue, hadoop (same order).
- CLI tool should take the inputs like register table to which branch? (if not mentioned use default branch) and also the source catalog and nessie catalog configuration.
- CLI tool should establish a connection to source catalog and nessie catalog using the configurations and perform migrations (There can be thousands of table or even more). It is expected to be migrated in seconds to minutes based on the resource available. 
- After migration table should not be available in the source catalog and should be available from the Nessie catalog and queryable.
- Should not touch or move the table's metadata/data files that are stored in fileSystem.

**Comment by Mehul2500** [comment]
Please refer to [PR #5297](https://github.com/apache/iceberg/pull/5297) (on Iceberg) for an API, helping to migrate Iceberg Tables from any Catalog (source) to any Catalog (Target).
