### ISSUE TITLE
Move nessie-demos to nessie

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1242]
Once the new repo https://github.com/projectnessie/nessie-demos has settled a bit more, remove the demos from the Nessie source tree to avoid confusion.

Also remove the python-demos-section from the `.github/dependabot.yml` file.

Maybe also add some link(s) to projectnessie.org and in the top-level `README.md`

**Comment by rymurr** [comment]
Will we move the demos out of that new repo and into the main repo too?

**Comment by tardunge** [comment]
So, the demos in the new repo are considered updated? I was following the python/demo in this repo and having some difficulties.

**Comment by rymurr** [comment]
Hey @tardunge what are the errors you are getting? Though, yes the ones in the demos repo are better to look at currently: https://github.com/projectnessie/nessie-demos

We will be updating the demos repo and moving the links soon.

**Comment by rymurr** [comment]
decision is to remove this directory, move the nessie-demos repo back to main repo. Also update docs

**Comment by snazy** [comment]
Closing due to lack of time - not urgent.
