### ISSUE TITLE
Python Nessie client should not need hash to create a branch

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1409]
currently `nessie.create_branch("etl", "main")` throws an error and `nessie.create_branch("etl", "hash of main")` works. For users sanity we should probably accept both cases to make life a bit easier for users.

**Comment by tardunge** [comment]
works fine for `nessie.create_branch("etl")` too when the ref is omitted.

**Comment by nastra** [comment]
We have talked about this internally and decided to not see this as an issue that needs fixing. From a user's perspective, the way to do it would be: `nessie.create_branch("etl", nessie.get_reference("main").hash_)`.
@tardunge thanks for bringing this up.
