### ISSUE TITLE
Change client parameter `auth_type` to `auth-type`

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1429]
This is to match other parameters in tools that use Nessie

**Comment by nastra** [comment]
Opened https://github.com/projectnessie/nessie/pull/1614 / https://github.com/projectnessie/nessie-demos/pull/109 / https://github.com/apache/iceberg/pull/2834 to address this

**Comment by snazy** [comment]
All three mentioned PRs are merged now, closing this

**Comment by nastra** [comment]
I forgot to update the latest status on this, but basically we were waiting until Iceberg 0.12.0 was released so that we can update Nessie docs for this. 
I'll create a PR for this shortly

**Comment by nastra** [comment]
https://github.com/projectnessie/nessie/pull/1806 is the PR required that I mentioned above
