### ISSUE TITLE
Code coverage and spark code

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1512]
It appears that the code that runs in spark (eg Delta, spark extensiosn) do not get accurate code coverage because spark executors don't have the jacoco agent running. We should look into how to do this correctly to measure code coverage accurately

**Comment by snazy** [comment]
Can we run the Spark executor in the same JVM?

**Comment by snazy** [comment]
Couple problems at play here:
* `maven-shade-plugin`  (for example in nessie-spark-extensions)
* Scala itself - all the artificial additional methods are reported with 0 coverage, 100% missed instructions, Same Scala class appearing "twice" (technically/byte-code correct though), etc.

**Comment by rymurr** [comment]
yes, jacoco warns that the bytecode doesn't match the source. I don't know
if that is shading or scala. I haven't found anything useful on either
while searching online.
