### ISSUE TITLE
Support filtering on all fields of EntriesResponse.Entry

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#1582]
Similar to how #1513 was fixed, we would like to filter on all fields of `EntriesResponse.Entry`. This is however currently not possible because the `Namespace` in  `ContentsKey` is currently annotated with `@JsonIgnore` and the `JacksonRegistry` in `cel-java` ignores this field.

**Comment by snazy** [comment]
@dimas-b is this what you fixed recently?

**Comment by dimas-b** [comment]
I think #4913 covers this.
