### ISSUE TITLE
Fix openapi examples

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1610]
the 'Try it Now!' button doesn't work for every endpoint b/c the example object doesn't render correctly and gets translated to the wrong url

`contents/{key}` was particularly bad in my testing.

**Comment by dimas-b** [comment]
Re-opening to add more example for current "not found" cases.

**Comment by dimas-b** [comment]
#1755 made more examples usable in Swagger UI.

At this point, only those API methods that require an existing commit hash will report "not found" in Swagger UI in a fresh Nessie server.
