### ISSUE TITLE
Flink Iceberg table create Error - com.dremio.nessie.client.rest.NessieBadRequestException: Bad Request (HTTP/400): getContents.ref

### ISSUE THREAD

**Issue by Blackmamba23** [projectnessie/nessie#1729]
Getting an error when trying to create an Iceberg table in Flink SQL client. Not sure if it is related to: [ Only accept NamedRefs in REST API (#1583) ]

**Comment by nastra** [comment]
@Blackmamba23 which version of Iceberg were you using?

**Comment by Blackmamba23** [comment]
Hi @nastra, was using Iceberg version 0.11.1. I switched to Nessie docker image version 0.7.0 and the error went away.

**Comment by Blackmamba23** [comment]
@nastra thats for your help mate! Looking forward to the new release
