### ISSUE TITLE
Pre-GA API "think-through"

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1804]
Before we release Nessie 1.0 GA, both the REST and gRPC APIs should be
1. "stable & good" and
2. "prepared" for future changes w/o breaking existing functionality & older (pre-GA) clients

This is rather a team-effort than a one-man-show.

The 1st point is about whether the API can already or is easy to adopt to known future needs: issues/feature that we already know about, like
* "relative references & hashes" (think: `main@12345678^5` referring to the 5th commit before the hash 12345678 on the main branch),
* "time-travel references" (think: `main@2021-08-10-00:00:00+0000`).
* are the OpenAPI types complete / easy / "worry-free" to extend

Especially for 2), we should have a common understanding of _how_ we want to tackle API changes.

The approaches for backwards-compatibility so far:
* version the API via the URI - i.e. have API endpoints at `/api/v1` - changes would go to e.g. `/api/v2`
  * lots of duplication on the server side
* expose the server version via the config-api
* custom HTTP headers via which both the client and server announce their versions
  * "commodity client" (think: swagger-ui)  don't work with this approach
  * tricky, because both the server and clients need to add a bunch of `if`s in a lot of places
* leverage `Content-Type` + `Accept` headers - i.e. _new/changed_ API endpoints use different media-types
  * only the affected API endpoints are "duplicated" on the server side
  * no change to clients (except of course implementing the new behavior/changes)
  * unclear how to port this to gRPC - maybe use different names in the gRPC service definitions
* ignore unknown fields in OpenAPI objects

**Comment by rymurr** [comment]
fix 500 error with Content-Type #1838

**Comment by rymurr** [comment]
if content type isnt json return 400 error

**Comment by dimas-b** [comment]
I've added some general API notes to #1767 (just happened to notice / think about some API rough edges while reviewing that PR)

**Comment by dimas-b** [comment]
Related issue: #2029

**Comment by dimas-b** [comment]
Related issue: #477

**Comment by ajantha-bhat** [comment]
`CreateReferenceBuilder` is confusing. We can refactor it to 

```
sourceRef(Reference ref) -> source reference name + optional hash on reference.
referenceName(String) -> new reference name.
```

**Comment by colan-dremio** [comment]
@ajantha-bhat for `CreateReferenceBuilder` you may want to keep `sourceRefName(String refName)` as an option, but enforce that exactly one of `sourceRef` or `sourceRefName` is specified. May help with backwards compatibility in some cases.

Also, strongly recommend `newReferenceName` over `referenceName` for clarity.

**Comment by colan-dremio** [comment]
@ajantha-bhat per our discussion in Slack, it would be nice if there was a fast and simple API to check if a commit hash exists anywhere in Nessie. I could imagine this being a standalone call with boolean return value, or trying to include it with `getReference`

**Comment by snazy** [comment]
Tracked via #5645
