### ISSUE TITLE
Iceberg: "protect" against accidental removal of assets

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#1925]
Iceberg's `Table` interface, as retrievable via `NessieCatalog.loadTable()`, gives access to "low level" Iceberg functionality like `ExpireSnapshots`, which would cause data loss or data corruption.

We should not allow users to "shoot themselves into the foot".

Snapshots for example will be safely "expired" via Nessie-GC, which also takes care of deleting "expired" data files.

Also investigate whether other Iceberg updates/actions like `DeleteFiles` or `ManageSnapshots` need to be "protected" as well.

**Comment by snazy** [comment]
Related: #855

**Comment by snazy** [comment]
Removed the 1.0.0 milestone, as it's not a "easy and straightforward task".

**Comment by rymurr** [comment]
> Removed the 1.0.0 milestone, as it's not a "easy and straightforward task".

I think you are right. I have added the milestone back on only so we can discuss in the meeting

**Comment by snazy** [comment]
Re-added to the 1.0.0 milestone

**Comment by snazy** [comment]
@ajantha-bhat this is very important for Nessie users

**Comment by ajantha-bhat** [comment]
@snazy : Agree, but Iceberg community didn't encourage having pluggable procedures or introducing the flag. 

I am thinking of hardcoding `gc.enabled = false` into table properties whenever Iceberg requests a `TableMetadata`.  
So that all the Iceberg native gc actions will fail when executed on these tables. 

I will followup and work on it this week.

**Comment by ajantha-bhat** [comment]
Just opened this at the Iceberg side.
https://github.com/apache/iceberg/pull/5718

**Comment by ajantha-bhat** [comment]
Completed.

**Comment by ajantha-bhat** [comment]
closing as completed as PR merged at the Iceberg side. We can track the Iceberg side release from this https://github.com/apache/iceberg/pull/5718
