### ISSUE TITLE
Document helm chart

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1980]

**Comment by nastra** [comment]
It's already documented in https://projectnessie.org/try/helm/, which also links to https://github.com/projectnessie/nessie/blob/main/helm/README.md

**Comment by rymurr** [comment]
We had discussed writing a blog post or a longer doc with a step by step deploy. 

A step by step guide with screenshots or commands to show:
* nessie running and exposed via a service or ingress (eg a curl or nessie cli command of a nessie url)
* connection to a keycloak deployed in same k8s w/ auth set up
* screenshot of prometheus collected metrics
* screenshot of jaeger trace
* some scaling commands

**Comment by snazy** [comment]
@adutra tackled this
