### ISSUE TITLE
Rename submit() to get() in Nessie API helpers

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2029]
As discussed in #2011 the `.submit()` call that makes API parameter builders execute actually API requests may be confusing as it may be interpreted as providing asynchronous behaviour.

Suggest renaming it to `get()` or `retrieve()`.

**Comment by snazy** [comment]
I think `submit()` is probably not the right verb for every API function and the "right" verb maybe depends on the function itself, so different for each function.

Unrelated to this issue: it sometimes happened to me that I refactored an old-API call like `tree.createReference("foo-branch")` to  `api.createReference().reference(Branch.of("foo-branch"));` and wondered why it didn't work... If someone has an idea how to add a custom inspection to IntelliJ for this, that would be great for usability.

**Comment by dimas-b** [comment]
> Unrelated to this issue: it sometimes happened to me that I refactored an old-API call like tree.createReference("foo-branch") to api.createReference().reference(Branch.of("foo-branch")); and wondered why it didn't work... If someone has an idea how to add a custom inspection to IntelliJ for this, that would be great for usability.

You can customize the `Result of method call ignored` inspection in IntelliJ IDEA, for example: class = `org.projectnessie.client.api.CreateReferenceBuilder`, method = `(?!submit).*` (repeat for all builder classes)

**Comment by snazy** [comment]
> customize the Result of method call ignored inspection in IntelliJ IDEA,

would be good to have that in `.idea`, wdyt?

**Comment by snazy** [comment]
If we rename `submit()`, I think using the actual verb from the builder interface would make sense. E.g. `TransplantCommitsBuilder.transplant()` instead of `TransplantCommitsBuilder.submit()`.
