### ISSUE TITLE
Support Hive table creation without specifying the `LOCATION` property 

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2030]
Currently in order to have Nessie, Iceberg and Hive integration working,  `LOCATION` property needs to be specified when creating the iceberg tables in Hive (external table) in order to execute MapReduce jobs, for example:
```
CREATE TABLE IF NOT EXISTS nba.salary
(Season STRING, Team STRING, Salary STRING, Player STRING)
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION '/user/nessie-warehouse/nba/salary'
TBLPROPERTIES ('iceberg.catalog'='nessie', 'write.format.default'='orc');
```

This is because when running MR jobs in Hive, without the `LOCATION`, Hive doesn't have the knowledge to know where the table is located. If possible, would be optimal if we can find a good workaround to have such table created without letting the user specifying `LOCATION` property.

**Comment by snazy** [comment]
Closing as "not planned" as things have changed w/ Iceberg REST.
