### ISSUE TITLE
Modify Delta to accept custom table names

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#205]
Currently Delta accepts only paths on a filesystem or hive table names as valid Delta tables. This makes it hard to pass to the NessieLogStore information about branch or hash. We have to modify nessie to accept table names in the format `<tablename>@<branch>#<hash>`.

This likely means we have to investigate how the `DeltaTable`s are cached as they are currently cached by path only.

**Comment by snazy** [comment]
Replaced with new umbrella #6815
