### ISSUE TITLE
Configure Quarkus Server 2.3+ to always use JSON for unexpected errors

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2108]
Quarkus PR https://github.com/quarkusio/quarkus/pull/20230 adds new configuration options to Quarkus 2.3 that allow applications to define the preferred content type for reporting unexpected errors.

For Nessie Server it makes sense to always report errors in JSON.

So, we should probably use the new config option when we upgrade to Quarkus 2.3+.

**Comment by snazy** [comment]
@dimas-b do we still need this issue?

**Comment by dimas-b** [comment]
LGTM now:
Server (not invalid OIDC port):
```
java -Dquarkus.oidc.auth-server-url=http://localhost:12345/auth/realms/master -Dnessie.server.authentication.enabled=true -Dquarkus.oidc.client-id=projectnessie -jar servers/quarkus-server/target/quarkus-app/quarkus-run.jar
```
Client:
```
$ curl http://localhost:19120/api/v1/config -H "authorization: Bearer invalid"
{"details":"Error id 92bddbfc-f5f8-4c05-ac55-5d0afe3af0f1-1","stack":""}
```
