### ISSUE TITLE
Rename/move AbstractTestRest

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2119]
Currently `AbstractTestRest` and `AbstractResteasyTest` are in the JAX-RS module/package.

However, these tests are not specific to JAX-RS, they use the java client and plain HTTP for invoking Nessie APIs. 

These tests are reused in other modules, e.g. Quarkus Server.

For the sake of clarity it would be nice to move these test to a more generic module and perhaps rename them to reflect their functionality more precisely.

**Comment by snazy** [comment]
Think, we're good now
