### ISSUE TITLE
Support configuring database adapters via Quarkus properties

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2148]
Currently database adapters created automatically by setting `nessie.version.store.type=...` get default values for all of their "common" properties, e.g. "key prefix".

Nessie should have a generic mechanism for configuring database adapters via Quarkus properties.

**Comment by snazy** [comment]
This change broke `SystemPropertiesConfigurer`, which relies on all the `with*()` methods.

I suspect, it's necessary to separate the Quarkus config from the `DatabaseAdapterConfig` hierarchy.
