### ISSUE TITLE
Investigate delays in Spark / Iceberg metadata refresh after a Nessie merge in CLI

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2165]
When a Spark/Iceberg session uses a long-lived branch name (e.g. `main`) and another user merges new changes into that branch from CLI or UI, the Spark session does _not immediately_ 'see' the new table metadata.

A forced "refresh" command may be required for the Spark session to reload updated table metadata.

**Comment by snazy** [comment]
@dimas-b Is this related to the Spark-Extensions using the REST API and not calling `refresh()` on the `UpdateableReference` in `:iceberg-nessie` ?

**Comment by dimas-b** [comment]
In my limited debugging session I did on this so far I did not observe _any_ calls to Nessie classes on the Spark/Iceberg side.

**Comment by dimas-b** [comment]
So I had to invoke the `REFRESH TABLE` command in Spark SQL to get it to reload fresh metadata from Nessie.

**Comment by snazy** [comment]
Yea, then it's that the Spark-SQL-Extensions don't call `refresh()`. Not sure how to solve this issue w/o having distinct SQL-Extensions implementations for Iceberg and Delta (to update the cached references).

Maybe by having some static field gets some "bridge"/"translator" injected that can do the job in either an Iceberg or Delta specific way? Some interface like
```
public interface CachedReferenceInvalidator {
  void updateReference(Catalog catalog, String reference);
}
```
The Iceberg implementation would then "peal" the `org.apache.iceberg.nessie.NessieCatalog` out of the catalog and update the reference. Delta in a similar way.
Any `NessieCatalog` class initialization would set the "static field" mentioned above. Might require another module on which the `spark-sql-extensions` and `:iceberg-nessie` and `deltalake-core` depend.

**Comment by dimas-b** [comment]
Re: reproducing, IIRC:

# Create a table in Spark / Iceberg on Nessie `main`
# Create a `dev` branch
# Insert into `dev` using a custom reference like `table@dev`
# Merge `dev` to `main` using Nessie CLI
# Select from `main` (current ref in Stark)
# Notice that the new data (from `dev`) is missing

**Comment by dimas-b** [comment]
In my use case I did _not) use Nessie Spark SQL extensions - just plain `spark-sql` shell with Nessie catalog and Nessie CLI (python client)

**Comment by nastra** [comment]
Is it possible that the table was created without the catalog prefix? See below example

```
spark-sql> create table test4(id int, name string);
21/10/05 09:55:10 WARN ResolveSessionCatalog: A Hive serde table will be created as there is no table provider specified. You can set spark.sql.legacy.createHiveTableByDefault to false so that native data source table will be created instead.
21/10/05 09:55:10 WARN HiveMetaStore: Location: file:/home/nastra/Downloads/spark-3.1.2-bin-hadoop3.2/spark-warehouse/test4 specified for non-external table:test4
Time taken: 0.085 seconds
```
```
spark-sql> show tables in nessie;
nba	salaries
nba	totals_stats
Time taken: 0.041 seconds, Fetched 3 row(s)
```
```
spark-sql> create table nessie.test5(id int, name string);
Time taken: 0.047 seconds
spark-sql> show tables in nessie;
nba	salaries
	test5
nba	totals_stats
Time taken: 0.025 seconds, Fetched 4 row(s)
```

Below are the tables not managed by the nessie catalog:
```
spark-sql> show tables;
21/10/05 09:57:13 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
default	test4	false
Time taken: 0.061 seconds, Fetched 2 row(s)
```

**Comment by snazy** [comment]
So there are "multiple sources" to run into this issue:
1. Use Nessie's SQL-Extensions: `USE target_branch` + `MERGE BRANCH source INTO target_branch`, which is understandably confusing to people
2. w/o the SQL-Extensions and perform the merge using e.g. the nessie-cli, which could be explained to people, but is still confusing.

In case of Iceberg, it might help to update `org.apache.iceberg.nessie.NessieCatalog#newTableOps` to refresh the `UpdateableReference`. WDYT?

**Comment by nastra** [comment]
This is most likely because `spark.sql.catalog.nessie.cache-enabled` is `true` by default. This means updating table `X` on `dev` and merging it into `main` doesn't refresh table `X@dev` or `X@main` since those are different tables to Iceberg in [this](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/CachingCatalog.java#L72-L76) piece of code.

**Comment by dimas-b** [comment]
In my env even table `X` (implied branch: `main`) was not refreshed after doing a merge in CLI. That was with Iceberg caching enabled.
