### ISSUE TITLE
Add integration tests that start the quarkus server with each backing store

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#217]
While testing, I realized that the dynamo backing store initialization within quarkus was broken. We need to get tests integration tests in place that actually test the stores in the server, not just independently.

**Comment by snazy** [comment]
Note: #718 adds this for the jdbc-store. It's more or less just adding another `<execution>` to the `native` profile's `maven-failsafe-plugin` and set the "right" environment variables that "adjust" the configuration.

**Comment by snazy** [comment]
Hm - actually not that easy as "just add some new Maven profile". Quarkus configurations when run via a JVM vs. Quarkus native-image builds vs. different (tiered-)version-store implementations requires more project-build-infra changes.

Hint: there's a `TODO.txt` in `versioned/tiered/` with some notes about the necessary configurations for JDBC-store integration-testing.
