### ISSUE TITLE
Use Quarkus's Mongo client instance instead of manually configured one

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#2236]
Relevant class (after PR #2176): `org.projectnessie.server.providers.QuarkusMongoDatabaseClient`

**Comment by dimas-b** [comment]
@snazy : As far as I can tell, the manually-configured `MongoDatabaseClient` is only used (after #2176) in Jersey tests and JMH runs, but those environments do not have Quarkus... Could you clarify what you meant to do under this issue?

**Comment by snazy** [comment]
Ugh - strike this. Don't know why I thought it didn't.
