### ISSUE TITLE
Add documentation about Nessie spark sql extensions

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#2239]
We can mention about the list of supported sql syntax from Nessie in [this](https://projectnessie.org/tools/)

We have demo which uses spark sql extensions. but it doesn't cover all the supported operations mentioned in [here](https://github.com/projectnessie/nessie/blob/main/clients/spark-antlr-grammar/src/main/antlr4/org/apache/spark/sql/catalyst/parser/extensions/NessieSqlExtensions.g4)

**Comment by snazy** [comment]
Isn't this #1979?

**Comment by ajantha-bhat** [comment]
yeah. It is duplicate. I will missed. I will close it.
