### ISSUE TITLE
Move %test Quarkus properties into test code

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#2240]
Refactor Nessie tests and move all `%test....` properties from `application.properties` to Quarkus test profile classes.

This will keep `application.properties` leaner.

Perhaps we should remove `%dev` properties from `application.properties` too.

**Comment by ajantha-bhat** [comment]
@dimas-b and @snazy  :  While going through Quarkus doc, I found we can have [profile-aware config files](https://quarkus.io/guides/config-reference#profile-aware-files).

so, If I do that also `application.properties` will slim down. 

Is that the expectation ? or I need to completely remove it from `application.properties` and hardcode them in below test profile itself ?
QuarkusTestProfileDynamo
QuarkusTestProfileInmemory
QuarkusTestProfileMongo
QuarkusTestProfileRocks

**Comment by snazy** [comment]
Let's move it into `QuarkusTestProfile`

The properties are still used, no?
