### ISSUE TITLE
Rename AS to FROM/TO in SQL Extensions

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#2272]
`CREATE BRANCH IF NOT EXISTS dev IN nessie AS base` is rather confusing and we should rename `AS base` to `FROM base`.

The same applies to `ASSIGN BRANCH dev AS base IN nessie`. Here it might make sense to use `TO base` instead of `AS base`

**Comment by dimas-b** [comment]
I'd suggested renaming `ASSIGN` to `REASSIGN`... a bit harder to read, but hopefully more specific and more intuitive. WDYT?

**Comment by omarsmak** [comment]
IMHO, I think `ASSIGN` is pretty clear about its intention. `REASSIGN` for me it feels longer and as @nastra mentioned, pretty specific

**Comment by nastra** [comment]
when I said `REASSIGN` seems a bit more specific I meant that in a positive way :)
