### ISSUE TITLE
Nessie commit logs from iceberg should have operations info aswell

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#2281]
inserting data to iceberg table in nessie catalog just says "iceberg commit", it can be more specific.

```
commit 432117cf261dcd4e5df65226b0b964fddf1ec6e56ba20456bc6410e148c0ad5d
Author:  <None>
Date: Wed Oct  6 18:18:30 2021 +0530

        iceberg commit

commit 936efca7e35eded94f1af4c575be4a86afe68f84d31a41bce793b5501be1083e
Author:  <None>
Date: Wed Oct  6 18:18:28 2021 +0530

        iceberg commit

commit 8d56deb7ad54ea1aee6420e6ccf8e268a17bc7f9d07db105287557aa7a72c3a7
Author:  <None>
Date: Wed Oct  6 18:15:49 2021 +0530

        iceberg commit
```

Also not sure why author is None.

Setup used: spark + nessie + iceberg

**Comment by ajantha-bhat** [comment]
@snazy:  sorry, I need a little more info to understand why it is a API change ? I thought it is just a change in commit message string `NessieTableOperations#doCommit`

a) dbname and table name is already there in metadata location. I can extract from there.
b) operations I meant are [iceberg operations](https://iceberg.apache.org/spec/#:~:text=certain%20snapshots.%20Possible-,operation,-values%20are%3A). As it is iceberg commit. This info is already present in snapshot summary on TableMetadata object at the point where are writing commit message string.

p.s : for create table Iceberg don't have operation mapped (as snapshot id is -1). So, I was thinking and didn't implemented this yet.

**Comment by ajantha-bhat** [comment]
> The API doesn't expose the Nessie operations as part of the commit-log.
I thought of using the iceberg [operations](https://iceberg.apache.org/spec/#:~:text=certain%20snapshots.%20Possible-,operation,-values%20are%3A) in the a commit message as it is commit from iceberg. so, I don't need Nessie operations. 

It is ok to use **iceberg operations** for **iceberg commit message** right ? Do you feel we need to use Nessie operation instead of iceberg operation ?

**Comment by snazy** [comment]
It is more complex than "just that". See all the sources that can end in `NessieTableOperations.doCommit`

**Comment by ajantha-bhat** [comment]
I know that for create table `snapshot.operation` will be null. I was also thinking the same way as you have fixed [here](https://github.com/apache/iceberg/pull/3257/files#:~:text=private%20String-,buildCommitMessage,-(TableMetadata%20base%2C%20TableMetadata) Except for schema change. 

Anyways thanks for fixing it. Please guide me next time or wait a bit more as I was also working on it.

**Comment by ajantha-bhat** [comment]
Fixed in https://github.com/apache/iceberg/pull/3257
