### ISSUE TITLE
Fix compatibility issues in spark-extensions

### ISSUE THREAD

**Issue by harshm-dev** [projectnessie/nessie#2328]
**What happened**: 
The code within spark extensions module has missed the compatibility fixes while the client and models were getting changed. This happened because the module uses old version of nessie - https://github.com/projectnessie/nessie/blob/58cc03d5b601bfa5c1fc9b6040f0c14fc7eb3cfd/pom.xml#L135.

**What you expected to happen**:
There should be a way to build code, that's compatible with latest nessie client by setting `client.nessie.version` in pom.xml

**How to reproduce it (as minimally and precisely as possible)**:
Set `client.nessie.version` to the nessie version - 0.10.2-SNAPSHOT at the time of raising this issue. Try to build the module, it'll fail with compilation errors.

> Can the client be always be built on the current code? That way, any breaking changes to the client will be caught. Iceberg project can always refer to the Nessie client version and bump it independently.

**Comment by snazy** [comment]
This will be tackled with tools-integration-testing -> closing.
