### ISSUE TITLE
Generate all configuration docs that used by Nessie

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2346]
Currently we maintain the configs manually in the docs. It will make sense at some point to automate this process by parsing the config annotations and generate all the config docs upon compiling the project (something similar to Quarkus and Camel)

**Comment by snazy** [comment]
Noting that Quarkus has some code to generate config docs as asciidoc in the `io.quarkus:quarkus-extension-processor` module, seems like `io.quarkus.annotation.processor.generate_doc.ConfigDocItemScanner` is a good entry point.
