### ISSUE TITLE
Verify how content-keys shall be filtered via CEL expressions

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#2367]
See https://github.com/projectnessie/nessie/pull/2364#discussion_r728165405

**Comment by snazy** [comment]
Pinging @dimas-b - do you think that we can close this one?

**Comment by dimas-b** [comment]
CEL filter params for entries (keys) and operations was unified in #4913

The current info exposed to CEL filters has use cases (e.g. #4912) so I think we ought to keep what is exposed ATM. I do not think we need to add anything for now either.

Closing as "done"
