### ISSUE TITLE
[Website] Add a "blog" section in Nessie website to increase the community awareness 

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2421]
I think it would be a good idea if we include a blog section in Nessie website where we can blog about new features, new releases, ideas, tips ..etc. I think this will help as well to increase the community awareness of project Nessie. Examples:

- Apache Camel blog ([link](https://camel.apache.org/blog/).
- Debezium ([link](https://debezium.io/blog/).
- Quarkus ([link](https://quarkus.io/blog/))

**Comment by pratyakshsharma** [comment]
I think this can be closed, now that we already have a blog section. @dimas-b

**Comment by dimas-b** [comment]
Yes (https://projectnessie.org/blog/). @omarsmak : I'm closing this issue. Please comment if you meant to add something specific to Nessie blog.
