### ISSUE TITLE
Upgrade spark3.version to 3.2.0 and adopt the code changes in Spark extensions

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2469]
There seems to be some needed code changes in Spark extensions in order to upgrade from 3.1.2 to 3.2.0, thus the code needs to be adopted.

**Comment by nastra** [comment]
latest Iceberg works already with Spark 3.2 (https://github.com/apache/iceberg-docs/pull/48/) so it's safe for us to upgrade as well

**Comment by snazy** [comment]
@omarsmak is this ticket still accurate?

**Comment by omarsmak** [comment]
> @omarsmak is this ticket still accurate?

I think it is no longer valid
