### ISSUE TITLE
Add integration tests for the Spark Extensions against spark versions Spark 3.0.x, 3.1.x and 3.2.x 

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2470]
Currently we have no mechanism to test different spark versions in Spark extensions. We should test Spark Extensions against Spark 3.0.x, 3.1.x and 3.2.x

**Comment by snazy** [comment]
@omarsmak Is this ticket still accurate?

**Comment by omarsmak** [comment]
> @omarsmak Is this ticket still accurate?

I am not sure as I lost track on that track. I think we can close it for now and reopen it again in case we think it is needed.
