### ISSUE TITLE
[CI] Make PR Github workflow triggered based on labels to avoid triggering the whole PR workflow for unrelated change

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2531]
Currently, the Github PR workflow `pull-request.yml` includes the build for the whole environments except the native build ('java', 'cli', 'ui' and 'site'). The drawback with this is that, sometimes it is not necessary to run the `java` checks when you only have `python` changes or when you have changes only related to the docs, it not necessary to run all the build for `java`, 'cli' and 'ui` .. etc. I think it would make sense if we label the changes and then trigger the github workflow based on the labels, something similar to [Iceberg](https://github.com/apache/iceberg/blob/master/.github/labeler.yml).

**Comment by snazy** [comment]
@omarsmak is this urgent or can we close it (for now)?

**Comment by omarsmak** [comment]
> @omarsmak is this urgent or can we close it (for now)?

Can be closed
