### ISSUE TITLE
UI: Nessie UI style broken

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#2594]
Current main

![image](https://user-images.githubusercontent.com/957468/140524798-32e0f374-bca4-4a1c-b4ae-63f5f5ef5a8b.png)

0.12.1:

![image](https://user-images.githubusercontent.com/957468/140524848-ea08c702-5325-49fd-9d10-d50c40f9fa30.png)

**Comment by nastra** [comment]
I think this changed with https://github.com/projectnessie/nessie/pull/2590

**Comment by nastra** [comment]
It looks like this was rather a bug than a feature and was fixed by https://github.com/react-bootstrap/react-bootstrap/issues/4771.

**Comment by nastra** [comment]
@rymurr do we want to fix it so that the style is as it was before?

**Comment by snazy** [comment]
It's still correct via Quarkus - but wrong in the webpack-dev-server via `npm run start`.
