### ISSUE TITLE
[CLI] Add a git-rebase-like approach for `nessie commit [keys]` when committing multiple keys in one commit

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2613]
Currently, when we have multiple keys, is the user make one file empty, it will be treated as Delete. However, this can lead to confusion and this, git-rebase-like where the user select which operation to edit and delete. Related to https://github.com/projectnessie/nessie/pull/2593#discussion_r744032260

**Comment by dimas-b** [comment]
It might be convenient to address #2392 as well, when we change how CLI gets user input for building a new commit.

**Comment by snazy** [comment]
Related: #3808

**Comment by snazy** [comment]
Closing as "not planned" as things have changed.
