### ISSUE TITLE
[CLI/Nessie Server] Prevent creating `ContentKey` from `empty or null` key in both Java API and Python API and investigate empty `ContentKey` life time 

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#2648]
Related comment: https://github.com/projectnessie/nessie/pull/2636#pullrequestreview-803612610

As well investigate what would happen if we have an empty `ContentKey` or `ContentKey` with empty elements in both, Java and Python APIs

**Comment by snazy** [comment]
Related: #3808

**Comment by snazy** [comment]
Empty elements are not allowed in `ContentKey`
