### ISSUE TITLE
How to use nessie from localhost?

### ISSUE THREAD

**Issue by be-rock** [projectnessie/nessie#275]
Hi,

Thanks for the great work on nessie, really looking forward to this project. 

Hoping you can help clarify the intent of using nessie on localhost....

```
$ docker run -p 19120:19120 projectnessie/nessie
...
2020-10-06 01:29:26,472 INFO  [io.quarkus] (main) nessie-quarkus 0.1-SNAPSHOT native (powered by Quarkus 1.8.1.Final) started in 0.030s. Listening on: http://0.0.0.0:19120
...
```

```
$ pip install pynessie
...
Successfully installed...
...

```

```
$ nessie create-branch my_branch
pynessie.error.NessiePermissionException: Not permissioned to view entity at : 403 Client Error: Forbidden for url: http://localhost:19120/api/v1/trees/branch/my_branch
```

Is the "Forbidden" error a result of not having logged into the UI at localhost? http://localhost:19120 redirects to http://localhost:19120/login but it is unclear where these credentials are actually *set*?

Does something need to be defined in `~/.config/nessie/config.yaml` before this will work?

Thanks again.

**Comment by jacques-n** [comment]
Auth should be off by default. Are you building locally or using the 0.1 published artifacts?

**Comment by jacques-n** [comment]
The steps you took work locally for me.

Window 1: docker run -p 19120:19120 projectnessie/nessie
Window 2: nessie create-branch my_branch

I've confirmed that I don't have anything in my `~/.config/nessie/`

**Comment by rymurr** [comment]
Hey @be-rock 

As of right now there is no auth on the REST endpoints so I find the 403 very perplexing. can you do me a favour and try
`curl --request POST http://localhost:19120/api/v1/trees/branch/my_branch2 -I`

Hopefully that will return `HTTP/1.1 204 No Content`. If this succeeds then we can narrow it down to something w/ the pynessie client. 

If it fails: do you have a proxy or something running that would inhibit talking via localhost?

**Comment by be-rock** [comment]
Hi @rymurr 

```
curl --request POST http://localhost:19120/api/v1/trees/branch/my_branch2 -I

HTTP/1.1 204 No Content
```

**Comment by be-rock** [comment]
```
python -m venv ~/.venv/nessie

~/.venv/nessie/bin/pip install pynessie
...
Successfully installed Click-7.1.2 attrs-20.2.0 certifi-2020.6.20 chardet-3.0.4 confuse-1.3.0 dataclasses-0.6 desert-2020.1.6 idna-2.10 marshmallow-3.8.0 marshmallow-oneofschema-2.1.0 mypy-extensions-0.4.3 pynessie-0.1.1 pyyaml-5.3.1 requests-2.24.0 simplejson-3.17.2 typing-extensions-3.7.4.3 typing-inspect-0.6.0 urllib3-1.25.10
```

Seeing the same behavior there.

```
~/.venv/nessie/bin/nessie create-branch my_branch
pynessie.error.NessiePermissionException: Not permissioned to view entity at : 403 Client Error: Forbidden for url: http://localhost:19120/api/v1/trees/branch/my_branch
```

**Comment by be-rock** [comment]
Ok, i did some digging and although there is no explicit proxy set on my machine, i do believe there may be some internal proxy set by a system administrator (not sure how) that i will need to try and figure out on my side. Thanks for all your help but I think we can close this as its looking more like a 'me' issue.

Thanks again.

**Comment by be-rock** [comment]
I seem to have a workaround. As mentioned, there is no explicit proxy set, something seems to be happening internally.

```
$ env|egrep -i 'http|proxy'
$

$ export no_proxy='localhost' && nessie create-branch my_branch

$ nessie list-references
[{"type": "BRANCH", "name": "my_branch", "hash": "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"}, {"type": "BRANCH", "name": "main", "hash": "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"}]
```

All good I'll close this out now. 👍

**Comment by rymurr** [comment]
Glad to hear you got it sorted @be-rock! Shout if you have any other questions/feedback :-)
