### ISSUE TITLE
More robust port detection in FlapdoodleMongoTestConnectionProviderSource

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#2860]
`FlapdoodleMongoTestConnectionProviderSource` currently determines the port that Mongo is running on by looking at the log output of the mongo daemon and checking for a particular regex.
When upgrading flapdoodle from `3.1.4` to `3.2.2` in #2840 the logging pattern changed and so the regex had to be updated.
It would be good to make that port detection code more robust by e.g. avoiding log parsing

**Comment by snazy** [comment]
Closed this one - see https://github.com/projectnessie/nessie/pull/2863#discussion_r765276811
