### ISSUE TITLE
Support custom authentication providers in the Nessie Client

### ISSUE THREAD

**Issue by harshm-dev** [projectnessie/nessie#2927]
Currently, Nessie supports only restricted set of authentication methods against the conf 'auth-type'. There could be times, when Nessie server is running behind an another proxy layer, which takes care of authentication. In such cases, the standard authentication providers may or may not be compatible. 

The ask here is to make the authentication provider configuration more open, by allowing the client to give a custom authentication provider implementation class, which implements [NessieAuthenticationProvider](https://github.com/projectnessie/nessie/blob/main/clients/client/src/main/java/org/projectnessie/client/auth/NessieAuthenticationProvider.java) interface. This way, the auth model is a lot more extensible.

Example conf
`--conf spark.sql.catalog.nessie.authentication.impl=com.company.XXAuthenticationProvider`

**Comment by dimas-b** [comment]
Currently the Nessie Java Client allows plugging in custom `NessieAuthenticationProvider` implementation via the `ServiceLoader`. Cf. [org.projectnessie.client.auth.NessieAuthenticationProvider](https://github.com/projectnessie/nessie/blob/nessie-0.17.0/clients/client/src/main/resources/META-INF/services/org.projectnessie.client.auth.NessieAuthenticationProvider)

It should be possible to add more resources that define custom `NessieAuthenticationProvider` implementations to the class path.

Does this help with your use case, @harshm-dev ?

**Comment by dimas-b** [comment]
You'd use `--conf spark.sql.catalog.<catalog_name>.authentication.type=CUSTOMTYPE`

**Comment by harshm-dev** [comment]
My observations:

The list of authentication providers are listed and picked up from [org.projectnessie.client.auth.NessieAuthenticationProvider](https://github.com/projectnessie/nessie/blob/main/clients/client/src/main/resources/META-INF/services/org.projectnessie.client.auth.NessieAuthenticationProvider) service file. Loaded by the code here - [NessieAuthenticationProvider.java#L56](https://github.com/projectnessie/nessie/blob/2b278b9ab2a080b8e2175001e35e02ee479584e4/clients/client/src/main/java/org/projectnessie/client/auth/NessieAuthenticationProvider.java#L56). If there's a new provider, it won't get into the list. Creating a new "org.projectnessie.client.auth.NessieAuthenticationProvider" file in a different jar also doesn't help as it depends on the classloader, which one gets picked first.

The fallback code however permits a custom authentication provider as far as it follows the package and class naming convention listed here [NessieAuthenticationProvider.java#L66](https://github.com/projectnessie/nessie/blob/2b278b9ab2a080b8e2175001e35e02ee479584e4/clients/client/src/main/java/org/projectnessie/client/auth/NessieAuthenticationProvider.java#L66).
For example, if auth type is `CustomCloud`, the authentication provider class name should be `org.projectnessie.client.auth.CustomcloudAuthenticationProvider`. 

Closing this issue, as there's a way to inject custom authentication provider in Nessie.

**Comment by dimas-b** [comment]
@harshm-dev : the code on line 56 that you referenced should normally loop over all `NessieAuthenticationProvider` classes mentioned in all service resources in _all_ jars of the _thread context_ class loader and then choose the first one that recognized the pre-configured `type` name. If this is not happening it is a bug :) Could you double check, please?

**Comment by harshm-dev** [comment]
@dimas-b Didn't work, only the first provider configuration file was picked.

I wasn't able to spot anywhere in the docs that providers can come from multiple files. It does mention multiple provider implementations, but doesn't mention multiple files. 

Not ruling out if I did a mistake in setting up the other jar. I'll try to dig more in the JDK code and update this thread.
