### ISSUE TITLE
401 Unauthorized when running Content Generator with "-u <URI>" and "-Dnessie.authentication.type" + "-Dnessie.authentication.token"

### ISSUE THREAD

**Issue by swillis12** [projectnessie/nessie#2943]
**What happened**:
When running Nessie content generator against a remote URL that requires authorization, the operation fails with 401 unauthorized.

**What you expected to happen**:
Should be able to pass authorization token successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Set the following environment variables:
```
NESSIE_URI=http://some_remote_uri_with_auth
NESSIE_TOKEN=remote_auth_token
```
Run the following (which will fail with a 401, authorization error):
```
 java -Dnessie.authentication.type=Bearer -Dnessie.authentication.token=$NESSIE_TOKEN -jar tools/content-generator/target/nessie-content-generator-0.17.1-SNAPSHOT.jar generate -u $NESSIE_URI -T 10 -n 1000 -t 10
```

**Details**:
- Nessie server type (docker/built from source) and version: Docker, Nessie 0.17.0
- Client type (Ex: UI/Spark/pynessie ...) and version: nessie-content-generator-0.17.1-SNAPSHOT.jar

**Comment by dimas-b** [comment]
Sorry, @swillis12 , I could not reproduce this failure :shrug: Let's sync up after the holidays.

**Comment by swillis12** [comment]
@dimas-b I am unable to reproduce this now. I will assume it was usage error on my part 🤷. Thanks
