### ISSUE TITLE
Validate read access to all reference names passed to API methods

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#3058]
Conceptually the Nessie authorization model relies on reference (branch/tag) names. It stands to reason that the user should have at least `READ` access to all references used in an operation.

ATM, for example, the`assignReference` method does not validate access to the `assignTo` reference, it only validates access to the reference being changed. https://github.com/projectnessie/nessie/blob/dea9dadaabe6b821814350f02ae39d2f4e4024ea/servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImplWithAuthorization.java#L129

This and possibly other use cases should be fixed to ensure access to all references used in API methods is validated.

**Comment by snazy** [comment]
This sounds like a quick fix in TreeApiImplWithAuthorization, right?

**Comment by dimas-b** [comment]
Sounds like a quick fix unless there are deeper implications (I did not check other use cases)
