### ISSUE TITLE
[CLI] Enable Mypy in PyNessie

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#3233]
It seems we don't have mypy enabled in PyNessie https://github.com/projectnessie/nessie/blob/main/python/tox.ini, thus the we don't do strict type checking.

**Comment by XN137** [comment]
isnt it "enabled" here?
https://github.com/projectnessie/nessie/blame/83f65148f08227d60ff6a5dcd23724ee6d08d211/python/tox.ini#L34

**Comment by omarsmak** [comment]
> isnt it "enabled" here? https://github.com/projectnessie/nessie/blame/83f65148f08227d60ff6a5dcd23724ee6d08d211/python/tox.ini#L34

True, didn't see that. Thanks for the heads up 👍🏽
