### ISSUE TITLE
antlr-runtime & IDEs

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3385]
In `nessie-spark-extensions-grammar` we (have to) relocate `org.antlr:antlr-runtime`, so our antlr-runtime does not conflict with other antlr-runtimes.

IntelliJ isn't "smart enough" to realize that the `org.antlr:antlr-runtime` dependency is relocated, so the source files that reference the relocated antlr-runtime cannot be built by IntelliJ.

@XN137 implemented a workaround (#3344) so that IntelliJ picks up the built `nessie-spark-extensions-grammar-*.jar`. I think, this is as good as it can get for now.

The downside of the workaround is that the `nessie-spark-extensions-grammar-*.jar` has to be built before the Nessie Maven project can be imported into IntelliJ.

This is where we reach the limitations of Maven + IntelliJ, because Maven has no way to "report" the actual model (unlike Gradle, which has a way to report such things to IntelliJ).

The only option that works all the time is to remove the relocation entirely from the Nessie project itself and release a separate, independent artifact that only contains the relocated antlr-runtime. Bumping antlr in Nessie would be a two-step process then - first release a new version of `org.projectnessie:nessie-antlr-runtime`, which follows the antlr version - then bump the antlr-version in Nessie.

**Comment by snazy** [comment]
Project to create the artifact: https://github.com/snazy/nessie-antlr-runtime
Branch with the change to Nessie: https://github.com/snazy/nessie/commits/antlr-runtime

**Comment by rymurr** [comment]
I am not such a huge fan of a separate repo. The extra logicsitcs, release artifacts/process etc is a lot of work for what is essentially an annoyance for developers in intellij.

In my experience this only comes up when someone is working directly with the extensions: eg not often. I have in the past just modified the import statements to refer to the original antlr and switched back before pushing to the PR. I don't find taht too un-ergonomic given we change these things every few months.

what do others think?

**Comment by snazy** [comment]
The problem before @XN137 merged the workaround was that IJ couldn't properly build, but not restricted to work on the spark-extensions but also other work - e.g. running 2 tests from different modules causes IJ to build the whole project, which failed.

The problem after the workaround is that the Jar must exist so that IJ can import the project. So the project must have been build before. I.e. it's not possible to just clone the Nessie repo + just open it in IJ.

antlr releases are rather rare (every couple months it seems). We can put the nessie-antlr-runtime project into the nessie repo (so no separate repo for it) - just separate GH workflows would be nice, because the release cycles are different and you can't re-release a version w/ sonatype.

other options that i tried to explore are:
* only activate the workaround when the jar exists - that didn't work, because a) maven profile activation should not use `project.*` properties, which would be mandatory and b) the `<activation><file>exists>` runs before e.g. `${project.version}` is available, so it doesn't work
* see whether IJ can conditionally run maven during import --> no
* see whether IJ can at least run a script when spark-antlr-grammar's changed --> no

**Comment by snazy** [comment]
Fixed via #3513
