### ISSUE TITLE
Refactor `StreamingUtil`

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3402]
`StreamingUtil` was intended to help users of the Java clients to use `Stream`s for commit-log, entries, etc.
Initially it was 2/3 methods with a few parameters, but evolved to have quite a few parameters per method now.

Instead of taking individual parameters, the methods in there should actually use builders - at best reusing the builders from `NessieApiV1` - either via a callback (think: `Consumer<GetCommitLogBuilder>`) passed into e.g. `getCommitLogStream` or by passing an already prepared builder into e.g. `getCommitLogStream`.

Goal: have less parameters for the methods in `StreamingUtil` and no need to change (think: break) the signature of these methods.

**Comment by tomekl007** [comment]
@snazy I see that those two methods:
```
  public static Stream<Reference> getAllReferencesStream(
      @NotNull NessieApiV1 api, OptionalInt maxRecords, @Nullable String filter)
      throws NessieNotFoundException {

    return new ResultStreamPaginator<>(
            ReferencesResponse::getReferences,
            (r, pageSize, token) ->
                builderWithPaging(api.getAllReferences().filter(filter), pageSize, token).get())
        .generateStream(null, maxRecords);
  }
```
and
```  
public static Stream<Entry> getEntriesStream(
      @NotNull NessieApiV1 api,
      @NotNull String ref,
      @Nullable String hashOnRef,
      @Nullable String filter,
      OptionalInt maxRecords)
      throws NessieNotFoundException {

    return new ResultStreamPaginator<>(
            EntriesResponse::getEntries,
            (ref1, pageSize, token) ->
                builderWithPaging(api.getEntries(), pageSize, token)
                    .refName(ref1)
                    .hashOnRef(hashOnRef)
                    .filter(filter)
                    .get())
        .generateStream(ref, maxRecords);
  }
```
are not used at all in Nessie's codebase. Can we remove them or is it possible that some downstream project (that has nessie as a dependency) uses them?

**Comment by snazy** [comment]
Ideally, those should be used by clients, but I suspect those are currently unused.
We don't have paging implemented on the server side yet - but the API supports it.
So I'd like to keep those methods and also make those "buildable".
