### ISSUE TITLE
Document non-production code that should be used only in integration tests.

### ISSUE THREAD

**Issue by tomekl007** [projectnessie/nessie#3414]
We have some source code, properties files, and more that reside in the `src` of the project but should not be used in the production code as they are intended for use only in (integration) tests.
We should document those to prevent accidental usage of this code in the production by our clients. For more info, see this conversation:
https://github.com/projectnessie/nessie/pull/3293#discussion_r809808744

**Comment by snazy** [comment]
Becomes superfluous after #5641 + after the removal of the database-adapter code later
