### ISSUE TITLE
Extended logs showing always the same metadata location

### ISSUE THREAD

**Issue by hpolloni** [projectnessie/nessie#3432]
**What happened**:
All commits on the "extended" log format (i.e. `nessie log -x`) show the same metadata location. The same for `/api/v1/trees/tree/{branch}/log?fetch=ALL`

**What you expected to happen**:
For commits to show the iceberg metadata location at the time of the specific commit. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a local instance of nessie. I tried with `mvn quarkus:dev`, docker and docker compose with MongoDB.
2. Setup pyspark following the same documentation. JARs are `org.apache.iceberg:iceberg-spark-runtime-3.1_2.12:0.13.1,org.projectnessie:nessie-spark-extensions:0.20.1`
3. Issue a CREATE, followed by a simple ALTER TABLE.

**Details**:
- Nessie server type (docker/built from source) and version: Repro in local quarkus, docker and docker-compose (mongo version)
- Client type (Ex: UI/Spark/pynessie ...) and version: pynessie and spark. 
- Spark version: 3.1.2
- Iceberg version: 0.13.1
- Nessie version: 0.20.1

**Comment by ajantha-bhat** [comment]
@hpolloni : **This is proper behaviour. Not an issue.** 
Because,

If the commit log from specific hash shows table metadata at the time of commit, then that file may not exist at the present time due to Iceberg's cleanup from `write.metadata.previous-versions-max` ([check here](https://iceberg.apache.org/docs/latest/maintenance/#remove-old-metadata-files))

For Iceberg table, Nessie maintains global state and on-reference state. ([read here](https://projectnessie.org/develop/spec/#on-reference-state-vs-global-state))

So, global state always points to latest metadata file and on-reference state points to snapshot id at the time of commit.
we can use the latest metadata file and that snapshot id to get the iceberg table state at the time of commit or use it for time travel. 

Hope it clears.

**Comment by hpolloni** [comment]
Hey @ajantha-bhat thanks for the explanation. I guess I wasn't being clear. I thought the problem that I was seeing is related to the way we are storing the metadata location, but according to your explanation this should work.

I have the following code. Basically this will do a `CREATE`, followed by an `ALTER` and a `USE REF`. I'd expect the table t1 to have a different schema after the `USE REF` but it doesn't. Both outputs are the same. Is this expected behavior?

This is the code that I'm testing with. 

```python
from pyspark.sql import *
from pyspark import SparkConf
import os

# for localhost/docker:
# url = "http://localhost:19120/api/v1"
# for minikube:
url = "http://192.168.64.2:19120/api/v1"

# Where to store nessie tables
full_path_to_warehouse = os.getcwd() + '/spark_warehouse'
# The ref or context that nessie will operate on (if different from default branch).
# Can be the name of a Nessie branch or tag name.
ref = "main"
# Nessie authentication type (BASIC, NONE or AWS)
auth_type = "NONE"

# here we are assuming NONE authorisation
spark = SparkSession.builder \
            .config("spark.jars.packages",
                "org.apache.iceberg:iceberg-spark-runtime-3.1_2.12:0.13.1,org.projectnessie:nessie-spark-extensions:0.20.1") \
            .config("spark.sql.extensions", 
                "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions") \
            .config("spark.sql.catalog.nessie.uri", url) \
            .config("spark.sql.catalog.nessie.ref", ref) \
            .config("spark.sql.catalog.nessie.authentication.type", auth_type) \
            .config("spark.sql.catalog.nessie.catalog-impl", 
                "org.apache.iceberg.nessie.NessieCatalog") \
            .config("spark.sql.catalog.nessie.warehouse", full_path_to_warehouse) \
            .config("spark.sql.catalog.nessie",
                "org.apache.iceberg.spark.SparkCatalog") \
            .config("spark.sql.catalog.nessie.cache-enabled", "false") \
            .getOrCreate()

print("Spark running")

spark.sql("USE nessie")
spark.sql("CREATE TABLE nessie.t1(c1 int)")
df = spark.sql("SHOW LOG IN nessie").toPandas()

# prev hash to alter. If we use this ref, then we 
# shouldn't see the alter (Unless I'm missing the semantics 
# of the USE REF AT).

h = df.loc[0]['hash']

spark.sql("ALTER TABLE nessie.t1 ADD COLUMN c2 double")

print(spark.sql("DESCRIBE TABLE nessie.t1").toPandas())

print("Using hash: %s" % h)
spark.sql("USE REFERENCE main AT %s" % h)
print(spark.sql("DESCRIBE TABLE nessie.t1").toPandas())


```

**Comment by ajantha-bhat** [comment]
@hpolloni : Thanks for reporting.

It seems `USE reference at hash` is buggy.
I just analyzed and raised this (https://github.com/projectnessie/nessie/issues/3439)

for time being, you can do like this.
describe table `t2@main#aa43b9236c998eb7123bf285668241acdd96e67671c12e8c9e0a5a8685b815d5`;
