### ISSUE TITLE
"Independent" sub-projects

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3438]
Related to #3385 and #3437

Rough idea:
* New top-level folder `independent` (or so) that contains all code that's independent from the "main" Nessie code.
  * Adjust Nessie main + PR CI to ignore changes to that folder
  * Remove the Gradle build support from Nessie CI
* Add antlr-runtime as an "independent" project (#3385)
  * Requires separate main + PR + release GH workflows
* Add the Maven+Gradle plugins as "independent" projects (#3437) 
  * Requires separate main + PR + release GH workflows with support for the Gradle build

**Comment by XN137** [comment]
any opinions on what kind of versioning scheme we should be using for these bootstrap/auxiliary projects?

**Comment by snazy** [comment]
> any opinions on what kind of versioning scheme we should be using for these bootstrap/auxiliary projects?

I think, we can start with the "next" Nessie version, but probably no need to keep those in sync afterwards.

**Comment by snazy** [comment]
Fixed via #3518 + #3513
