### ISSUE TITLE
Incorrect rendering of code examples on projectnessie.org

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#3464]
e.g.
![image](https://user-images.githubusercontent.com/40603221/156017844-10a2c1ca-027a-4346-ada6-16693e86f331.png)

**Comment by XN137** [comment]
the problem seems to happen when the "```" closing block has a different indentation as the opening one:
https://github.com/projectnessie/nessie/blame/187859163a6000d32a79cc972f8d68cbccdc6fe7/site/docs/tools/iceberg/spark.md#L55-L83

**Comment by XN137** [comment]
https://github.com/projectnessie/nessie/pull/3465 was merged and CI on main has deployed the new site which no longer has the problem:
![image](https://user-images.githubusercontent.com/1204398/156150581-a1ff33e1-8cdd-411b-8838-d27e6327a7d5.png)

**Comment by dimas-b** [comment]
The formatting is fixed - thanks!

However, IIRC we used to have tabbed browser elements alternative between different languages in the same "space" on the page, but now language panes are listen sequentially :shrug:

**Comment by snazy** [comment]
Yea - I also think, that we had tabbed code blocks.

**Comment by dimas-b** [comment]
Feel free to open a separate issue if you prefer. From my POV we might as well reopen this one.

**Comment by snazy** [comment]
@XN137 is this still an issue?

**Comment by XN137** [comment]
> is this still an issue?

looking at https://projectnessie.org/tools/iceberg/spark/ yes there still are no tabbed browser elements for code examples.
i've never seen them myself but you guys claim it used to render differently in the past.
i am guessing some library upgrade for the site generation changed this behavior but imo not very important to get this fixed.
