### ISSUE TITLE
Merge fails if more than 20 commits are present on the source branch

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#3466]
* Start Nessie server with `quarkus:dev`
* Create a new branch `test1`
* Start a local Spark (1 node is sufficient)
* Make more that 20 commits in `test1`
* Attempt to merge `test1` to the default branch
* Observe an error similar to the following:
```
[...]
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.175 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.163 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.165 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.184 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.143 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.138 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.191 seconds
```
```
$ nessie  merge test1 -c 2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d
Client Error Not Found: Commit '2b2a3501e5c50ce7b5ba562d4a932c0f9509d08ab019953c89ec9491e0b1dea6' not found (Status code: 404)
Requested URL: http://localhost:19120/api/v1/trees/branch/main/merge?expectedHash=2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d
Server status: 404
Error code: REFERENCE_NOT_FOUND
Server message: Commit '2b2a3501e5c50ce7b5ba562d4a932c0f9509d08ab019953c89ec9491e0b1dea6' not found
Server traceback: None
```
Note: the hash from the error message is not visible in Nessie commit logs in CLI.
Note: the hash from the merge error is different in each new merge attempt without making any other commits.

**Comment by ajantha-bhat** [comment]
I found the problem, 
`AbstractDatabaseAdapter#copyCommits` is preparing new commit hashes for merged commits. 

During this time, for new commits that are merging if the `keylist` size is reached, we are writing the new keylist to backend store [`buildIndividualCommit-> buildKeyList`]. 
While writing keylist we are using common code that queries commit log from backend db. But these new commit hashes are not present in the backend db. Hence the error. 

solutions:
a) Don't query backend db, use the list of commits that are present (but keylist and parent list are individual configuration, it can cause problems when both are configured different value)
b) use old commit hashes to query the keylist (need to change many common code interfaces for this)
c) write individual commit for merge (Oops, this will screw up multi table transaction) 

so we need to go with a) or b) I guess.
