### ISSUE TITLE
Store new commit hashes in  reflog for merge/transplant

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#3497]
Merge and transplants creates new commit hashes for each new merging or transplanting commits. 
So, while debugging issues, we might have to know how these hashes came to the target branch. 
So, store them in reflog.

a. For transplant, currently source commit hashes (with old commit hash id) are stored in reflogEntry#getSourceHashes
Need to store new commit hashes in that place.

b. For merge, only the new commit head is stored in reflogEntry#getSourceHashes.
Need to store all new commit hashes in that place.

**Comment by snazy** [comment]
Reflog entries for commit et al are deprecated -> closing
