### ISSUE TITLE
Use kryo instead of java serialization for the `Reference` used in Spark

### ISSUE THREAD

**Issue by tomekl007** [projectnessie/nessie#3585]
As a follow-up after:
https://github.com/projectnessie/nessie/pull/3561#pullrequestreview-905457313
We should try to use `kryo` serialization mechanism.

Steps to do it:
1. Revert whole #3561
2. remove Serializable from Reference.java
3. run the testcase `AbstractRestGCTest` , it will fail with `serializable` exception.
4. explore using Kryo or a custom serializer for Reference.

**Comment by snazy** [comment]
@tomekl007 do we still need this ticket?
