### ISSUE TITLE
Add authorization checks for Namespaces

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#3633]
https://github.com/projectnessie/nessie/pull/3572 added support for Namespaces and the goal of this PR is to add authorization checks for creating/reading/deleting namespaces.

**Comment by dimas-b** [comment]
Currently Namespaces fall under the same authZ checks and any other content object (tables, views, etc.)

**Comment by dimas-b** [comment]
Will use the standard authZ checks that apply across all entity types for now.
