### ISSUE TITLE
Avoid messing with Namespaces via TreeApi directly

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie#3634]
https://github.com/projectnessie/nessie/pull/3572 introduced a new `NamespaceApi` that allows creating/reading/deleting Namespaces with additional checks whether for example a Namespace is empty before it can be deleted.
However, currently there's no mechanism in place that would prevent users from messing with Namespaces directly via the `TreeApi` and bypass those checks from the `NamespaceApi`. The idea here is that we need a mechanism to avoid bypassing those checks.

**Comment by dimas-b** [comment]
With API v2, the java client is going to provide helper classes for manipulating `Namespace` objects (#5004).

However, operations on `Namespace` contents can still be used in commits via the normal "commit" APIs. That is how client-side namespace helpers are going to be implemented. In terms of REST, all content changes will be going through the "commit" API.

What that means for this issue, is that we cannot prevent users from messing with `Namespace` contents via REST API. IMHO, this is ok, though.
