### ISSUE TITLE
The load and loadDefinition for NessieViewCatalog always return latest view info

### ISSUE THREAD

**Issue by springald** [projectnessie/nessie#3734]
**What happened**:
The loadDefinition and load in NessieViewCatalog return unexpected results in some cases.

**What you expected to happen**:
When I call loadDefinition or load a view, I should not always get the info of the latest view.
The NessieViewCatalog should fetch the version and return the expected version.

**How to reproduce it (as minimally and precisely as possible)**:
Create branch A and create view V1 on it.
Create branch B from branch A and update view V1 on branch B  to V2.
When I call loadDefinition or load the view V2 on branch B, I will get the correct results.
When I call loadDefinition or load the view V1 on branch A, I will get the same result as V2.

**Details**:
- Nessie server type (docker/built from source) and version:
Build from source. 0.22
- Client type (Ex: UI/Spark/pynessie ...) and version:
NessieViewCatalog

**Comment by dimas-b** [comment]
@springald : Thanks for starting a discussion on this issue.

Could you be more specific about the exact pieces of data that are "correct" or "incorrect" from your point of view?

Please note that the metadata location is considered _global_ state in Nessie and affects all content objects regardless of branch.

In that regard the notes on "view" in https://projectnessie.org/develop/spec/#view look a bit out-of-date to me... Was that the source of confusion?
