### ISSUE TITLE
StreamingUtil.getCommitLogStream is ignoring OptionalInt maxRecords

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#3766]
`AbstractRestCommitLog#commitLogPagingAndFilteringByAuthor
`
`completeLog` size should be same as `pageSizeHint`, but it is total log size.

https://github.com/projectnessie/nessie/blob/main/servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/AbstractRestCommitLog.java#L395

Note:
Also need to verify other api in StreamingUtil for `pageSizeHint`

**Comment by ajantha-bhat** [comment]
Testcase is already there as mentioned in the PR desvription

https://github.com/projectnessie/nessie/blob/main/servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/AbstractRestCommitLog.java#L401

After line 401, just need to add an assert that completeLog.size() == pageSizeHint to see the issue.

**Comment by dimas-b** [comment]
Re: `assert that completeLog.size() == pageSizeHint` strictly speaking the server does not _have_ to honour page size _hints_... it's just a suggestion coming from the client, but the server has authority over the page size.
