### ISSUE TITLE
GC: Check and remove commitProtectionDuration in gcParams

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#3768]
GC identify has two steps.
1. to identify live contents and fill to bloom filter
2. Identify expired contents.

currently for step 2, `commitProtectionDuration` is used to avoid the new commits or in-progress commits to be expired.
here we can check the commits against the cutoff time per reference itself (which is used in step 1).
**Only check the contents that are in older than cutoff time against the bloom filter.**

So, we can never test live contents (also new contents) against the bloom filter.

**Comment by snazy** [comment]
That protection-time is meant to protect _data_ that has "just been written" - it's not to "protect commits" (as you said).
You have to prevent that e.g. _new_ snapshots in a table-metadata are _not_ expired.
