### ISSUE TITLE
Drop Python 3.7 ?

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#3932]
(This is rather a question than a requirement.)

Is Python 3.7 still a thing in the wild or could we drop support for it?

We've seen a bunch of recent version-bump PRs that fail to pass CI. The most recent one is #3927, that runs into the following dependency "hell" for Python 3.7 (3.8 and newer are fine):
```
Error: ERROR: Cannot install -r /home/runner/work/nessie/nessie/python/requirements.txt (line 18), -r /home/runner/work/nessie/nessie/python/requirements_dev.txt (line 21), -r /home/runner/work/nessie/nessie/python/requirements_dev.txt (line 23) and -r /home/runner/work/nessie/nessie/python/requirements_dev.txt (line 28) because these package versions have conflicting dependencies.
  
  The conflict is caused by:
      click 8.1.2 depends on importlib-metadata; python_version < "3.8"
      flake8 4.0.1 depends on importlib-metadata<4.3; python_version < "3.8"
      pytest 7.1.1 depends on importlib-metadata>=0.12; python_version < "3.8"
      sphinx 4.5.0 depends on importlib-metadata>=4.4; python_version < "3.10"
  
  To fix this you could try to:
  1. loosen the range of package versions you've specified
  2. remove package versions to allow pip attempt to solve the dependency conflict
```

If we drop support for Python 3.7, that would affect the Nessie Demos as well.

Pinging @XN137 @omarsmak @keithgchapman

**Comment by XN137** [comment]
https://devguide.python.org/#status-of-python-branches

3.7 is EOL only at 2023-06-27
also i think some big LTS distros use it as their primary python version.
so i would lean towards not dropping support for 3.7.

```
flake8 4.0.1 depends on importlib-metadata<4.3; python_version < "3.8"
sphinx 4.5.0 depends on importlib-metadata>=4.4; python_version < "3.10"
```
the error states that these 2 versions of libraries are marked as not compatible through transitive dependencies by their authors.
thus when we want to install them into the same environment we have to chose upgrading one over the other.
in theory flake8 could release a new version with this dependency not capped, but until then we have to solve the problem differently.

solutions imo:
- we could pin sphinx to 4.4.0
- we could change our CI to run linting in another venv than docs generation

i think its fine that dependabot suggests a dependency upgrade and our CI (more so pip) tells us that this upgrade is not compatible with another library.
this kind of problem can happen even when we drop 3.7 support.
if our docs are generated fine there is also no strong need to keep upgrading sphinx (its not like we get any security fixes or the like).

**Comment by omarsmak** [comment]
I am not as well in favor of dropping 3.7 support as @XN137 mentioned, EOL is still pretty much until next year and many are using it.
The question is, why do we need at the first place to lint and generate docs on every Python version? I think one Python version is enough for these. Then the Python versions matrix could be used only to test building the wheel and running the pytests (to make sure the CLI works on every supported Python version).

**Comment by snazy** [comment]
See also #5574

**Comment by XN137** [comment]
in tox we only run linting on python 3.8
https://github.com/projectnessie/nessie/blob/2839f66071791153e134444a047f3c645e1e1cb2/python/tox.ini#L20-L26

but flake8 is part of the basedev requirements so is installed always:
https://github.com/projectnessie/nessie/blob/2839f66071791153e134444a047f3c645e1e1cb2/python/requirements_basedev.txt#L23

if flake8 was in `requirements_lint.txt` we could potentially upgrade to v6 without CI errors

**Comment by snazy** [comment]
Seems like we dropped Python 3.7 a while ago
