### ISSUE TITLE
Migrate Python desert to marshmallow-dataclass

### ISSUE THREAD

**Issue by omarsmak** [projectnessie/nessie#4093]
We are using [desert](https://github.com/python-desert/desert) to generate the marshmallow schemas from Python dataclasses. However, I am having concern about the project maintenance state as it seems to me it is not as active as before and thus, it will make sense to switch to something with better maintenance support. Therefore, I would suggest we migrate to [marshmallow dataclass](https://github.com/lovasoa/marshmallow_dataclass) since it seems has better maintenance and more frequent updates overall.

**Comment by XN137** [comment]
if this involves a lot of changes we could also consider using https://github.com/samuelcolvin/pydantic instead (which seems to be more modern as its integrated with python3 type annotations and also seems to be more popular nowadays).

**Comment by omarsmak** [comment]
> if this involves a lot of changes we could also consider using https://github.com/samuelcolvin/pydantic instead (which seems to be more modern as its integrated with python3 type annotations and also seems to be more popular nowadays).

The change from [desert](https://github.com/python-desert/desert) to [marshmallow dataclass](https://github.com/lovasoa/marshmallow_dataclass) is pretty straightforward and minimal since both are based on marshmallow. Therefore, I am in favor of the easier upgrade unless there is good advantages of using pydantic over marshmallow

**Comment by XN137** [comment]
https://pypistats.org/packages/marshmallow
https://pypistats.org/packages/marshmallow-dataclass
https://pypistats.org/packages/pydantic

less dependencies, more popular, based on modern python idioms

> There's no new schema definition micro-language to learn. If you know how to use python type hints, you know how to use pydantic. Data structures are just instances of classes you define with type annotations, so auto-completion, linting, [mypy](https://pydantic-docs.helpmanual.io/usage/mypy/), IDEs (especially [PyCharm](https://pydantic-docs.helpmanual.io/pycharm_plugin/)), and your intuition should all work properly with your validated data.

https://pydantic-docs.helpmanual.io

as i said, my suggestion was only if the migration required a bunch of changes which would be equivalent with switching libraries.
if its a simple switch it probably does not matter.
