### ISSUE TITLE
Helm transactional version store type support

### ISSUE THREAD

**Issue by kerossin** [projectnessie/nessie#4214]
I guess this is more of a question regarding deployments with Helm.

Is deployment of Nessie with transactional version store type not supported with Helm or just nobody has gotten around to implementing it yet?

Or is it enough to just specify `versionStoreType: TRANSACTIONAL`  and it should work?

**Comment by nastra** [comment]
TBH we haven't tried `TRANSACTIONAL` via Helm. It's very likely that required parameters that have been introduced with e86e4c6f are not passed properly to the Nessie server.

**Comment by kerossin** [comment]
Does this https://github.com/projectnessie/nessie/pull/4223 help?

I don't actually use Nessie myself, I was just asked to try and update the Helm chart so I can't really test if it works how it should.

At least with an empty postgres:14-alpine DB Nessie starts and the web UI works.

**Comment by dimas-b** [comment]
It looks like we may want to refactor `TRANSACTIONAL`. Currently we have tests for both Postgres and H2, but only Postres can be used in runtime (more verbose comments in #4223)

**Comment by kerossin** [comment]
https://github.com/projectnessie/nessie/pull/4223 merged
