### ISSUE TITLE
Support H2 also as quarkus version store type and refactor properties.

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4224]
nessie.version.store.type= TRANSACTIONAL is directly mapped to postgres
https://github.com/projectnessie/nessie/blob/main/servers/quarkus-cli/src/main/resources/application.properties#L23-L24

In future if we want to support some more transactional backend store, configuration may become confusing. 

So, rename the TRANSACTIONAL enum to POSTGRES and add H2 (similar to how we support Non-Transactional).

**Comment by dimas-b** [comment]
We need to double check how Quarkus handles JDBC drivers... It may pre-package them at build time. I'm not sure, if this is how it works, though.

**Comment by snazy** [comment]
Not planned for the foreseeable future.
