### ISSUE TITLE
Refreshing UI after visiting a branch or tag gives 404

### ISSUE THREAD

**Issue by naren-dremio** [projectnessie/nessie#423]
Due to how react works and there isn't any route for `/tree/main/` or any other path other than / refreshing a page wouldn't work as it doesn't know how to serve it. A way to solve this is to route requests to index.html and for webpack this can be done via `navigateFallback` or if someone chooses to use nginx we can use a rewrite rule too.

Since we are using create react app and webpack config is within `node_modules/react-scripts/webpack.config.js` we need to move it out.. Not sure if this is worth to move it outside.. or is this all handled by quarkus?

**Comment by laurentgo** [comment]
I guess some of it would have to be handled by Quarkus and BrowserRouter would have to be provided with the base address for the UI in order for routing to work correctly in SPA?
