### ISSUE TITLE
Migrate from OpenTracing to OpenTelemetry

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#4231]
Nessie uses OpenTracing artifacts directly. However, the OpenTracing [project](https://opentracing.io/) has been archived and its front page advises migrating to [OpenTelemetry](https://opentelemetry.io/docs/migration/opentracing/).

**Comment by snazy** [comment]
#5605 + #5607 

#5608 is the remaining task for this one

**Comment by dimas-b** [comment]
What about supporting `otlp/2`? Do we want that? Was it just my env. that was [broken](https://github.com/projectnessie/nessie/pull/5605#pullrequestreview-1202569450)?
