### ISSUE TITLE
Helm chart integration testing

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4235]
The Nessie Helm chart recently had an issue, which went undetected into a release. Those issues should be caught earlier.
Maybe we can leverage [Chart Testing](https://github.com/helm/chart-testing) for integration tests, at best using a matrix of different Nessie server backend databases (Dynamo, Postgres, Mongo) and Helm versions (those that are relevant to our Helm chart).

/cc @nastra

**Comment by nastra** [comment]
I added some very basic helm testing with a few version stores that don't require additional setup (inmemory, rocksdb). Over time we can probably add mongo/postgres and such but those require that e.g. a mongo process is actually running somewhere
