### ISSUE TITLE
"You need to enable JavaScript to run this app." when doing a curl against Nessie UI

### ISSUE THREAD

**Issue by eskhisov** [projectnessie/nessie#4278]
**What happened**:
I deployed Nessie in AWS EKS.  I enabled Ingress and I am using AWS Load Balancer Controller version 2,4,1.  The ingress provided URL in the form k8s-xxxxxxx-nessie-xxxxxxxxx-xxxxxxxx.us-east-1.elb.amazonaws.com
When I use this URL in browser (chrome and Edge), I get the HTML in attached response.html.txt.

Needless to say, Jvascript is enabled in my browser.

**What you expected to happen**:
When I use URL in browser or Postman, I expect to get Nessie page back

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the latest version of AWS Load Balancer as described here: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/
I used attached values.yaml where I updated "ingress" section

**Details**:
- Nessie server type (docker/built from source) and version: latest helm chart
- Client type (Ex: UI/Spark/pynessie ...) and version:
[values.yaml.txt](https://github.com/projectnessie/nessie/files/8732927/values.yaml.txt)
[response.html.txt](https://github.com/projectnessie/nessie/files/8732963/response.html.txt)

**Comment by nastra** [comment]
@eskhisov how does the request and the request URL exactly look like? I wonder if it's something similar to what's being reported in https://stackoverflow.com/questions/59875150/postman-you-need-to-enable-javascript-to-run-this-app. I don't have a way currently to try this with AWS EKS so it's difficult to say what's wrong exactly.

**Comment by nastra** [comment]
I was able to reproduce this via `curl` (but not via the Browser) with a local ingress example with Minikube (#4286).

```
$ curl chart-example.local
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link href="/favicon.ico" rel="icon"/><meta content="width=device-width,initial-scale=1" name="viewport"/><meta content="#000000" name="theme-color"/><meta content="Nessie Repository Manager" name="description"/><link href="/logo192.png" rel="apple-touch-icon"/><link href="/manifest.json" rel="manifest"/><link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet"/><link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/><title>Nessie</title><script defer="defer" src="/static/js/main.34e97d9c.js"></script><link href="/static/css/main.3d9a3219.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
```

Requests to the underlying REST API are not affected, so it's just the React UI.

```
$ curl -X GET chart-example.local/api/v1/trees/tree
{
  "type" : "BRANCH",
  "name" : "main",
  "hash" : "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d"
}
```

**Comment by nastra** [comment]
In fact this doesn't have to do anything with Ingress. Just serving the UI locally via `./mvnw quarkus:dev` and doing a curl on `http://localhost:19120/` will show the same issue.

**Comment by nastra** [comment]
@eskhisov are you blocked by this? I'm surprised that this doesn't work for you in the Browser. Also can you please try with Ingress paths using `"/"` instead of `"/*"`?

**Comment by eskhisov** [comment]
@nastra Sorry, it is 7:50am my time, just got to work :-) Yes, part of the work is blocked.  I do get this result when I use browser.  Let me try "/".
![image](https://user-images.githubusercontent.com/4778589/169543835-c1ecc9fa-7781-4998-94e1-6efaf69c911c.png)

**Comment by nastra** [comment]
fwiw, I see that response in the very first request in my Browser as well but the UI still loads and works

**Comment by eskhisov** [comment]
Switching to "/" from "/*" does not change anything.  Also, making API call returns 404.

**Comment by nastra** [comment]
If REST API calls return 404 then something is off with your Ingress configuration. This issue here is only affecting curl/postman requests against the UI, not the actual REST API of Nessie. Can you give an example of a failing API Call?

**Comment by eskhisov** [comment]
http://k8s-mlingest-nessie-ae904d3f4e-1532794151.us-east-1.elb.amazonaws.com/api/v1/trees/tree/main?fetch=MINIMAL

**Comment by eskhisov** [comment]
Ok, fixed the problem.  The final version of ingress parameters in values.yaml that did the trick:

```
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: "*.us-east-1.elb.amazonaws.com"
      paths:
        - /*
  tls: []
```
