### ISSUE TITLE
Can Iceberg's Table's  UUID be used as content id?

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4287]
It will be nice if the Iceberg's Table's  UUID (`TableMetadata#uuid`) be used as content id.
This way we can map the table end to end.

**Comment by snazy** [comment]
Content-IDs are assigned on the server side - not by clients.
With Iceberg metadata in Nessie, the Icberg table UUID will implicitly become available via Nessie

**Comment by ajantha-bhat** [comment]
> Content-IDs are assigned on the server side - not by clients. 
With Iceberg metadata in Nessie, the Icberg table UUID will implicitly become available via Nessie

We can send it from client to server? as we have an interface too that accepts content-id.

**Comment by snazy** [comment]
Nope. It's a Nessie specific ID that has nothing to do with Iceberg's table ID. And content IDs should really only be generated on the server side.

**Comment by snazy** [comment]
Nessie server has the authority over the content-ID generation, neither Iceberg nor any other client.
