### ISSUE TITLE
Unify references to Iceberg / Spark versions in docs

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#4349]
Different docs pages reference different Iceberg / Spark / etc. versions, which can confuse users.

Search for `iceberg-spark-runtime`.

**Comment by pratyakshsharma** [comment]
I can take this up as well :)

**Comment by dimas-b** [comment]
@pratyakshsharma : feel fee :+1: Please note that the docs might have already been fixed in many places since this issue was filed.

**Comment by snazy** [comment]
@dimas-b i think we good with this one now?
