### ISSUE TITLE
Does nessie support flink via iceberg use s3 protocol acess object storage(minio,ceph)? 

### ISSUE THREAD

**Issue by ming12713** [projectnessie/nessie#4373]
**flink-sql shell**

`sql-client.sh embedded -j /jar/iceberg-flink-runtime-1.14-0.13.1.jar -j /jar/bundle-2.17.178.jar -j /jar/url-connection-client-2.17.178.jar shell`

**create catalog**
`
CREATE CATALOG s3_catalog WITH (
  'type'='iceberg',
  'catalog-impl'='org.apache.iceberg.nessie.NessieCatalog',
  'uri'='http://nessie:19120/api/v1',
  'ref'='main',
  's3.endpoint'='https://obs.uisee.com',
  'warehouse'='s3://warehouse'
);
`

**create tables** 
```
Flink SQL> CREATE TABLE s3_catalog.flink.t1 (id BIGINT COMMENT 'unique id',data STRING);
[ERROR] Could not execute SQL statement. Reason:
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
```

**Comment by nastra** [comment]
@ming12713 can you try and also specify `'io-impl'='org.apache.iceberg.aws.s3.S3FileIO'`? It should work with that
