### ISSUE TITLE
How to restore main branch

### ISSUE THREAD

**Issue by don1559** [projectnessie/nessie#4413]
**What happened**:
After dropping main branch everything doesn't work. How to reset main back ?

spark.sql("DROP BRANCH main IN dev_catalog")

Now can't create a branch (main or dev) or tables and UI doesn't show anything.

Tried nessie cli:
sudo nessie config --add default_branch main

but nothing happened.

When trying to create a branch using spark:
: org.projectnessie.error.NessieReferenceNotFoundException: Named reference 'main' not found
	at org.projectnessie.error.ErrorCode.lambda$asException$1(ErrorCode.java:45)

**What you expected to happen**:
Expect to be able to restore main branch easily 

**How to reproduce it (as minimally and precisely as possible)**:
spark.sql("DROP BRANCH main IN dev_catalog")

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:
docker running on K8
nessie 0.30.0
spark 3.2.1

**Comment by ajantha-bhat** [comment]
- From the Java API it is possible to restore it as shown below,

https://github.com/projectnessie/nessie/blob/main/servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/AbstractRestReferences.java#L60  

- From spark sql, code always looks for the default branch during create reference. Hence you got that error. 
Agree that it is confusing and **We should probably provide a way for it.**

- Do you have any other branch when main is deleted? 
If you have, then in the spark configuration you can probably set default branch as that branch and restart the spark session.
`conf.set("spark.sql.catalog.dev_catalog.ref", "thatBranch") `

**Comment by don1559** [comment]
Thanks for the fast reply.
- No there was only main branch when dropped
- Suggestion to not be able to drop main using spark sql unless -F for example + allow recreating the main branch/ref.
- Were able to restore main using Nessie CLI:
Did a **nessie reflog** in order to find some commit hashes
then I looked into the oldest one (the one the catalog was created with)
and then I typed: nessie branch -f main 2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d

**Comment by snazy** [comment]
#3401 should finally help in such scenarios.
