### ISSUE TITLE
Java Nessie http client does not follow HTTP/308 redirects

### ISSUE THREAD

**Issue by tmnd1991** [projectnessie/nessie#4428]
**What happened**: 
When invoking any `NessieApiV1` method which gets a response code 3xx (for example to redirect http to https) I get:

```
java.lang.UnsupportedOperationException: Unknown status code 308.
```

**What you expected to happen**:

I would expect that the client correctly performs the redirection.

**How to reproduce it (as minimally and precisely as possible)**:

I can reproduce it connecting to my Nessie instance, but I'm working on a reproducer into Nessie unit tests

**Details**:
- Nessie server type (docker/built from source) and version: 0.30.0
- Client type (Ex: UI/Spark/pynessie ...) and version: Spark/Java

**Comment by snazy** [comment]
@tmnd1991 Thanks for the issue and PR.
Not against this change, but could you elaborate when the redirect actually happens?

**Comment by snazy** [comment]
Hm - I wonder why the change's actually necessary, because the default for `java.net.HttpURLConnection#getInstanceFollowRedirects` is `true`. The only case when Java's implementation doesn't work is HTTP/308 (see `sun.net.www.protocol.http.HttpURLConnection#followRedirect`).

**Comment by tmnd1991** [comment]
I see it happening when redirecting from http to https, might it be? without the patch applied I get the 308 error I mentioned

**Comment by snazy** [comment]
Closing this one, because we have Java's new HTTP client in `:nessie-client` now.
