### ISSUE TITLE
Review and update commit information (e.g. message) created for merge + transplant operations

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4430]
See discussion in https://github.com/projectnessie/nessie/pull/4333#issuecomment-1148805078

**Comment by snazy** [comment]
@dimas-b can we call this part of API v2?

**Comment by dimas-b** [comment]
Looks like a good thing to do in API v2. Added to #5112

**Comment by snazy** [comment]
Let's keep this issue open even after #5686. The idea for this ticket is to have a better _default_ message.

Current idea is to switch from the current default to e.g. `Merged N commits from foo-branch at 1234567890abdef`

**Comment by dimas-b** [comment]
Moved this to #5645
