### ISSUE TITLE
Internal Server Error (500) on missing content type header - should be 400

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#4436]
```
$ curl -X POST http://localhost:19120/api/v1/trees/branch/main/commit -d ''
{
  "status" : 500,
  "reason" : "Internal Server Error",
  "message" : "javax.ws.rs.NotSupportedException: RESTEASY003065: Cannot consume content type",
  "errorCode" : "UNKNOWN",
  "serverStackTrace" : null
}
```

Should be "Bad Request" `400`.

**Comment by dalaro** [comment]
Hi.  I had a look at this, thinking it might make a good first contribution to the project.

For background, it seems `curl` defaults to POSTing `application/x-www-form-urlencoded` in this case:

```
$ curl --verbose -X POST http://localhost:19120/api/v1/trees/branch/main/commit -d ''
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:19120...
* Connected to localhost (127.0.0.1) port 19120 (#0)
> POST /api/v1/trees/branch/main/commit HTTP/1.1
> Host: localhost:19120
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 415 Unsupported Media Type
< Content-Type: application/json
< content-length: 191
< 
{
  "status" : 415,
  "reason" : "Unsupported Media Type",
  "message" : "RESTEASY003065: Cannot consume content type",
  "errorCode" : "UNSUPPORTED_MEDIA_TYPE",
  "serverStackTrace" : null
* Connection #0 to host localhost left intact
```

If `curl` instead sends `Content-Type: application/json`, then Nessie responds with 400 Bad Request, as desired:

```
$ curl --verbose -H 'Content-Type: application/json' -X POST http://localhost:19120/api/v1/trees/branch/main/commit -d ''
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:19120...
* Connected to localhost (127.0.0.1) port 19120 (#0)
> POST /api/v1/trees/branch/main/commit HTTP/1.1
> Host: localhost:19120
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 0
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< validation-exception: true
< Content-Type: application/json
< content-length: 236
< 
{
  "status" : 400,
  "reason" : "Bad Request",
  "message" : "commitMultipleOperations.expectedHash: must not be null, commitMultipleOperations.operations: must not be null",
  "errorCode" : "BAD_REQUEST",
  "serverStackTrace" : null
* Connection #0 to host localhost left intact
}
```

Looking at current Nessie behavior (especially in `NessieExceptionMapper`), the RESTEasy method-matching implementation, and the relevant bit of the JAX-RS spec, perhaps we should change the first case's response to 415 Unsupported Media Type.  The `NotSupportedException` thrown by Resteasy would normally correspond to status 415, but that exception falls through to [`NEM`'s general else-case](https://github.com/projectnessie/nessie/blob/nessie-0.30.0/servers/rest-services/src/main/java/org/projectnessie/services/rest/NessieExceptionMapper.java#L79-L86) and gets converted to a 500 Internal Server Error before the client sees it.

Out of curiosity, I wondered whether we could hypothetically give the client a hint about why this is failing, like "accepted Content-Type(s): application/json; but received Content-Type was application/x-www-form-urlencoded".  I realize this might be a bad idea even if possible, so I just had a tentative peek at it.  Doing it in a robust way that's driven by annotations and programmatically generated looks significantly trickier than just changing `NEM`.  RESTEasy's internals, especially [`SegmentNode#match`](https://github.com/resteasy/resteasy/blob/4.7.5.Final/resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java#L367-L385) have enough information to generate this type of message, but it looks non-trivial to reconstruct that information elsewhere.  Maybe there's a way to interrogate `ResteasyContext` for this info in a pre-match container request filter, but I think it would be brittle.  So, I set that idea aside after finding no great options.

Here's a PR that changes the response status/reason from 500 ISE to 415 Unsupported Media Type, with some tests: https://github.com/projectnessie/nessie/pull/4711

**Comment by snazy** [comment]
@dalaro can this issue be closed?

**Comment by dalaro** [comment]
@snazy I should have closed it immediately, sorry about that.  I'll try to mind multiple closures between linked issues/PRs more closely.
