### ISSUE TITLE
Nessie Catalog Export/Import/Migration between Nessie servers 

### ISSUE THREAD

**Issue by vemulapalli-aditya4** [projectnessie/nessie#4470]
**Description**:

The goal is to create Nessie Catalog Export/Import/Migration between Nessie servers, which may be of different versions  and may be using different backends for the store.

**Comment by ajantha-bhat** [comment]
@vemulapalli-aditya4 : Can we use the original ticket instead of creating new one?
https://github.com/projectnessie/nessie/issues/4012

**Comment by vemulapalli-aditya4** [comment]
Ok sure.
