### ISSUE TITLE
Enforce reasonable size limits

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4550]
Objects like `ContentKey` or `Key` and are currently unrestricted in their serialized size, without throwing an error.

Especially for objects `ContentKey` or `Key` we should enforce a size limitation to prevent internal structures to become inefficient. I suspect that it is fine to restrict fully qualified table names to maybe 500 characters.

**Comment by dimas-b** [comment]
The 500 chars default max length sounds reasonable to me.
