### ISSUE TITLE
Support for foundationDB backend store.

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4576]
**Description**:
Support [foundationDB](https://www.foundationdb.org/) as one of the NoSQL backend stores.

**Expected Use Cases**:
Snowflake and Firebolt currently use foundationDB backend store.
Delta seems to also consider this (https://github.com/delta-io/delta/issues/867).

Note: It is not urgent but good to have support.

**Comment by snazy** [comment]
Don't see a major demand for it. Closing.
