### ISSUE TITLE
Support Spark 3.3

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4668]
Apache Iceberg already supports Spark 3.3 - so it's about time to support Spark 3.3 in Nessie as well.

**Comment by tmnd1991** [comment]
I see that the support for spark 3.3 might be very near for `main` branch, do you have any ETA for the next minor release that will include it?
Thanks

**Comment by snazy** [comment]
> I see that the support for spark 3.3 might be very near for `main` branch, do you have any ETA for the next minor release that will include it? Thanks

@tmnd1991 I can't promise any date, but I hope we'll release again soon - been a while now since the last release.
