### ISSUE TITLE
SQL Extension CREATE TAG does not "honour" USE REFERENCE

### ISSUE THREAD

**Issue by tmnd1991** [projectnessie/nessie#4685]
**What happened**:
On a spark session after `USE REFERENCE develop` (i.e. we "checkout" the `develop` branch) when a `CREATE TAG tagName` is issued the tag is created on the head of the default branch (usually `main`).

**What you expected to happen**:
I would've expected the tag created from the HEAD of the `develop` branch.

**How to reproduce it (as minimally and precisely as possible)**:
TBD.

**Details**:
- Nessie server type (docker/built from source) and version: 0.30.0 docker
- Client type (Ex: UI/Spark/pynessie ...) and version: Spark

**Comment by snazy** [comment]
Such a change makes sense to me.
Looks like `ASSIGN` also defaults to the default-branch instead of the one configured by `USE`.
