### ISSUE TITLE
Efficiency: key lists may contain deleted keys

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#4772]
Nessie maintains key lists in storage for efficient content look up by key.

However, those key lists may contain deleted keys, which is sub-optimal.

Note: there's no visible effect of this issue at the API level since the deleted keys are pruned based on the `Delete` operations stored in the commit that references the key list.

How to reproduce:
* Apply the source path below to commit `ac765be3c74dc52c0b33e07a0e018f3bd1305409`
* Run Nessie Server as: `java -Dnessie.version.store.advanced.key-list-distance=1 -Dnessie.version.store.advanced.max-key-list-size=0 -jar servers/quarkus-server/build/quarkus-app/quarkus-run.jar` (the parameters speed up key list creation)
* Create two `Put` commits for the same key
* Observe log entries similar to these:
```
Put: create-contents-2022-07-22-16-00-48.contents.0
Put: create-contents-2022-07-22-16-00-48.contents.0
Key list key: create-contents-2022-07-22-16-00-48.contents.0
```
* Delete the key
* Observe log entries similar to these:
```
Delete: create-contents-2022-07-22-16-00-48.contents.0
Key list key: create-contents-2022-07-22-16-00-48.contents.0
``` 

Notice that the key list written during the processing of the "delete" operation contains the deleted key, which is redundant.

----

Test case patch:
```
diff --git a/versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java b/versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java
index 90625b204..15b621fc8 100644
--- a/versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java
+++ b/versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java
@@ -232,6 +232,13 @@ public abstract class AbstractDatabaseAdapter<
       throw new ReferenceConflictException(String.join("\n", mismatches));
     }
 
+    commitParams.getPuts().forEach(p -> {
+      LOGGER.warn("Put: {}", p.getKey());
+    });
+    commitParams.getDeletes().forEach(k -> {
+      LOGGER.warn("Delete: {}", k);
+    });
+
     int parentsPerCommit = config.getParentsPerCommit();
     List<Hash> newParents = new ArrayList<>(parentsPerCommit);
     newParents.add(branchHead);
@@ -1606,6 +1613,12 @@ public abstract class AbstractDatabaseAdapter<
 
   @VisibleForTesting
   public final void writeKeyListEntities(OP_CONTEXT ctx, List<KeyListEntity> newKeyListEntities) {
+    newKeyListEntities.forEach(e -> {
+      e.getKeys().getKeys().forEach(k -> {
+        LOGGER.warn("Key list key: {}", k.getKey());
+      });
+    });
+
     try (Traced ignore = trace("writeKeyListEntities").tag(TAG_COUNT, newKeyListEntities.size())) {
       doWriteKeyListEntities(ctx, newKeyListEntities);
     }
```

**Comment by dimas-b** [comment]
#4773 could be used for deletes

**Comment by snazy** [comment]
Can you re-try and do the "delete" in the commit right before the commit that contains the key-list?
The key-list is generated for all the commits _before_ the commit w/ the key-list - in other words: the key-list contains the state for all commits _excluding_ the current one.

**Comment by dimas-b** [comment]
> the key-list contains the state for all commits excluding the current one.

Yes, this is not a correctness issue, but an optimization issue. My point is that we could drop the deleted key(s) from the list entirely because those entries are not relevant as of the commit that contains the deleted _and_ happens to contain the key list.

**Comment by snazy** [comment]
Well, my ask was to verify the key-list generated _after_ the commit with the delete-op. Deleted keys don’t make it into the aggregated key-list.

**Comment by dimas-b** [comment]
However, when #4592 is implemented this issue will become a moot point.

**Comment by dimas-b** [comment]
> [...] to verify the key-list generated after the commit with the delete-op
Here's the log:
```
Put: create-contents-2022-07-25-14-28-13.contents.0
Put: create-contents-2022-07-25-14-28-13.contents.0
Key list key: create-contents-2022-07-25-14-28-13.contents.0
Delete: create-contents-2022-07-25-14-28-13.contents.0
Key list key: create-contents-2022-07-25-14-28-13.contents.0
Put: create-contents-2022-07-25-14-28-43.contents.0
Put: create-contents-2022-07-25-14-28-43.contents.0
Key list key: create-contents-2022-07-25-14-28-43.contents.0
```
So, the deleted key is removed from latter key lists.

Still, it seems like putting the key into a key-list at put #2 and the last put is still redundant because the same data is available from the commit itself (minor point).

**Comment by snazy** [comment]
I guess we can close this since the new storage model is in and the old one's already deprecated.
