### ISSUE TITLE
Proper paging for "list of references" API

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#4813]
Currently, getting a "list of references" [appears](https://github.com/projectnessie/nessie/blob/73e52c99a8542a55ceee8405b3018e079278ad72/servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java#L133) to return all reference in one page.

Nessie ought to respect user-provided page size hints and pagination tokens in this API.

**Comment by snazy** [comment]
Fixed via #5641
