### ISSUE TITLE
ReferenceRetryFailureException should be a separate Nessie Exception.

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4856]
Currently, 
`ReferenceRetryFailureException` extends `ReferenceConflictException`. 
So, even without an actual conflict, Nessie can throw `NessieReferenceConflictException` when the retry timeout happens because of a busy backend store. 

As the exceptions are sent from server to client as the error code [409, REFERENCE_CONFLICT], the underlying cause is eaten. 
Hence user only gets the `NessieReferenceConflictException` and thinks that there is an actual conflict. (As java doc says this exception is thrown when the hash associated with a named reference does not match with the hash provided by the caller)

**Comment by ajantha-bhat** [comment]
Hmm, the error message says retry has failed. 
`NessieReferenceConflictException: Retry-Failure during commit against `

Maybe that is enough. Just the java doc of `NessieReferenceConflictException` is confusing.

**Comment by dimas-b** [comment]
I'm not sure the client can meaningfully distinguish the case of "retry failure" and the case of a genuine concurrent modification by another process. I think in both cases the right approach for the client would be to reset to the latest `HEAD` of the branch and redo the "transaction".

In this regard, having a dedicated client-facing error code (and exception class) might cause more confusion than benefit, I guess :thinking: 

+1 to clarifying javadoc, though.
