### ISSUE TITLE
Update site docs and Nessie demo to use latest Iceberg (0.14.0) and latest Nessie (0.41.0)

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#4900]
Can also use the latest spark-3.3 in the examples and demo instead of spark-3.2.

**Comment by XN137** [comment]
note that this should also allow us to get rid of this workaround again:
https://github.com/projectnessie/nessie-demos/blob/ceca57e14a3610ed4c86a8886e72c505f03ab0c1/notebooks/tests/test_nessie_iceberg_hive_demo_nba.py#L32-L33
(also exist in the related notebook)

**Comment by XN137** [comment]
https://github.com/projectnessie/nessie-demos/commit/3c714c360f15c2cdff9dda44cd9ed843a85338e7 can be used as a guideline
