### ISSUE TITLE
REST API to fetch the Date of Repository Initialization or Date of First Commit

### ISSUE THREAD

**Issue by swillis12** [projectnessie/nessie#4993]
**Description**: Requesting the ability to know either the date of the first commit or when the repository was initialized.

**Requested Changes in public API**:
- Changes in REST API

**Expected Use Cases**: In a UI when showing a date picker for selecting a commit before a certain time, this would help to disable irrelevant dates. E.g. if the repo was initialized on Aug 24, 2022, we can grey out/disable dates before that time so that the user cannot select them.

**Comment by snazy** [comment]
We do have an internal "property bag" for the repository (`RepositoryDescription`), for things that rarely change.
The creation date of the repository could be stored there and exposed via a REST API

**Comment by dimas-b** [comment]
Good point! I was thinking about server properties in the `/config` end point, but adding a dedicated endpoint to return a `RepositoryDescription` is even better.

**Comment by snazy** [comment]
Not sure whether it’s good to return the whole object or the whole map. Rather a property in RD exposed via /config as an Instant
