### ISSUE TITLE
code-coverage delta check has lost value since migrating to gradle

### ISSUE THREAD

**Issue by XN137** [projectnessie/nessie#5058]
since switching to gradle the code coverage delta check in CI has become semi-useless, because depending on the changes in the commit/PR only a subset of tests are being run.

thus comparing code coverage between 2 commits on `main` for example may show a big delta, simply because not the same set of tests was run. for example:
https://app.codecov.io/gh/projectnessie/nessie/commit/51348700a955ddc15620d6cdab2522aa9aa21a7b

this also affects build on the main branch, why is why this view has a few failed checks usually:
https://github.com/projectnessie/nessie/commits/main

the team discussed this and we decided to remove the code-cov delta check for the java parts due to this.
note that for python we want to keep it since it should still provide accurate numbers (since all tests run if python tests run).

as a follow-up we should figure out a way how we can get the latest repo-wide code coverage number including all tests.
some ideas:
- dedicated nigthly build that is forced to run all the gradle tests
- let every N-th commit on `main` run all gradle tests automatically (i.e. by clearing the gradle cache)

**Comment by snazy** [comment]
Side note: It's rather "caused" by the removal of `jacoco` from the projects that purely contain tests.

**Comment by snazy** [comment]
Note: I suspect, it's actually caused by #5100
