### ISSUE TITLE
Support cachable REST responses

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#5111]
A bunch of REST requests could be cached. HTTP level caching could help UIs. This ticket is more about keeping these things in mind to "not close the door" for caching, than actually implementing it. However, it might be easy to implement it - but maybe it's not.

A cachable REST response requires that a request has the following characteristics:
* Cachable request method: `HEAD`, `GET` - in the far future also `QUERY`. Not cachable: `POST`, `PUT`, `DELETE`
* Request is an "exact point query". Means, only requests against a specific commit-ID plus potentially specific content-keys can produce cachable responses.
* Non-cachable requests (examples):
  * get current default branch incl. HEAD commit ID
  * references to HEAD
  * commit log from HEAD
* commit log requests might be cachable, if the request for a "commit log page" does not target HEAD

**Comment by dimas-b** [comment]
I guess we have to provide explicit `Cache-Control` headers.

It might work for `HEAD` as well, if we set the max age appropriately. With a reasonably low max age caching can be effective, while repective concurrent changes "eventually" (the caller does not know if there are concurrent changes anyway).

Also, clients that demand fresh data can still do so with `Cache-Control: no-cache`

**Comment by snazy** [comment]
Let's close this issue for now.
