### ISSUE TITLE
Sparse representation of trees with DynamoDB backend

### ISSUE THREAD

**Issue by rdettai** [projectnessie/nessie#518]
**Observation:**
The L1 and L2 nodes of the object tree have a dense representation when serialized to DynamoDB. Each of them is designed to have a size so that the entire object is close to 4KB:
- 151x20B for L1, leaving room for other fields such as the parents list
- 199x20B for L2.

AWS counts every 1KB written as a write unit (no matter whether the table is set to OnDemand or Provisioned). This means that writing an L1 or L2 object will cost 4 unit, no matter how many child the node actually has. If you are manipulating a catalog with only a few entries (e.g an Iceberg catalog with a few tables), you are wasting up to 75% of your write capacity / cost.

**Proposition:**
The tree field could have two possible representations: one with a MAP for sparse trees and one with a LIST when usage gets greater than x% of the nodes size. Computing optimal x is easy: 
- key value pairs add an extra 3 bytes for the key + 1 byte fix cost [1]
- values are 20 bytes long
- x*(4 + 20) = SIZE*20
- x=125 for L1 and x=165 for L2

One could go even further into the optimization by choosing between MAP and LIST encoding of every 1KB increment:
- 0-x1 MAP || x1-1KB LIST || 0-x2 MAP || x2-2KB LIST || 0-x3 MAP || x3-3KB LIST || 0-x4 MAP || x4-1KB LIST

But this is probably overkill:
- If we want the encoding to be optimal for the dynamo cost structure, it will likely be easier to use a custom encoding saved as a binary blob in the tree field 😃
- the most significant gain (75%) comes from the case with very little entries

[1] This is not very explicit in the official doc but explained here: https://medium.com/@zaccharles/calculating-a-dynamodb-items-size-and-consumed-capacity-d1728942eb7c

_Unrelated note:_ I think that L1 objects are likely to exceed 4KB if their parent list is full or close to full (151 in the tree + 49 parents * 20B + field names and other fields). But I don't think that this is a big issue as it should only occur in very rare conditions.

**Comment by snazy** [comment]
Superseded by #1638
