### ISSUE TITLE
Proper paging for getEnties API

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5312]
Based on TODO comments in [TreeApiImpl](https://github.com/projectnessie/nessie/blob/c054cc98c7897653065c75d8dfcbfaedd7ae2a97/servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java#L550)

At the moment, we do not expect that many keys/entries to be returned.
So the size of the whole result is probably reasonable and unlikely to "kill" either the
server or client.

In API v1 the server has to process all entries to derive implicit namespaces.

In API v2 (#5112) the server will not have to derive implicit namespaces, therefore paging over entries should be possible.

**Comment by snazy** [comment]
Fixed via #5641
