### ISSUE TITLE
Validate Namespace existence during commits

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5426]
Currently Nessie Servers allow creating tables with keys like `a.b.C`, implying that `a.b` is a namespace.

Iceberg, for example, expects namespace `a.b` to exist after the table is created.

In Nessie, `Namespace` objects have content IDs, which means they have to be created explicitly in order for the ID to be assigned.

API v1 provides ways to retrieve `Namespace` objects even for namespaces that do not have IDs. However, those "implicit" `Namespace` objects are not visible in all APIs and their handling is somewhat cumbersome on the server side (e.g. required full enumeration of entity keys).

For the sake of consistency Nessie Servers should validate `Namespace` object existence and deny changes that refer to unknown keys.

The checks should be done as least on `Put` of a content object without a content ID (creation).

The Iceberg-side `NessieCatalog` should automatically create `Namespace` objects during table creation to match current user expectation.

Related issue: #3832 

Note: creating `Namespace` objects with the same key in different branches will cause conflicts if a merge is attempted. This is existing behaviour. Enforcing `Namespace` existence will not affect merge checks, but may make merge conflicts more prevalent.

**Comment by snazy** [comment]
Dup of #6244, PR is #6246
