### ISSUE TITLE
SQLExtensions: Support creating a branch from a commit.

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#5474]
Support creating a branch/tag from a commit. Currently, only creating from reference names is supported (https://projectnessie.org/tools/sql/#grammar).

Recently, one of the users wanted to create a new branch with an ancestor hash. 
I have suggested a workaround of CREATE BRANCH + ASSIGN BRANCH.

**Comment by dimas-b** [comment]
API v2 (#5112) should naturally support this by allowing `DETACHED` references in the `createBranch` payload... but let's keep this issue for tracking the related use cases separately.

**Comment by dimas-b** [comment]
Note that authorization checks may put extra restrictions on `DETACHED` references.

**Comment by ajantha-bhat** [comment]
> API v2 (https://github.com/projectnessie/nessie/issues/5112) should naturally support this by allowing DETACHED references in the createBranch payload... but let's keep this issue for tracking the related use cases separately.

I think V1 also might support it (not sure though). But the issue we are talking about here is just the SQL syntax. SQL syntax just accepts reference name (not a commit hash or ref@hash)

**Comment by snazy** [comment]
This is a duplicate of #4666 , right?

**Comment by ajantha-bhat** [comment]
> This is a duplicate of https://github.com/projectnessie/nessie/issues/4666 , right?

True. Missed it.
