### ISSUE TITLE
Trino support for project nessie with Apache Iceberg

### ISSUE THREAD

**Issue by code-magician323** [projectnessie/nessie#5528]
**Description**:
I'd like to query Apache Iceberg table with Trino, but my Iceberg table is configured with Nessie catalog. I'd like to understand if/ how can I integrate that with Trino.

**Expected Use Cases**:
Pretty much everything I do with Iceberg, I expect doing that using Trino

**Comment by ajantha-bhat** [comment]
Hi @code-magician323,
We do have an open PR on the Trino side to support Nessie catalog (https://github.com/trinodb/trino/pull/11701).
But the response from the community is pretty slow. 

Can you please raise this feature request in Trino community? I believe once many people start asking for Nessie, because of the attention, PR can get reviewed fast.

**Comment by ajantha-bhat** [comment]
cc: @bitsondatadev

**Comment by jebnix** [comment]
@ajantha-bhat To emphasize the need for this, I currently don't use Nessie at my workplace only because of the lack of support in Trino.

**Comment by jebnix** [comment]
I think that this issue is the main reason Nessie doesn't get the attention it deserves in the data engineers community. Without enabling Trino usage, there's not much one can do in the subject when one wants to use Nessie.

**Comment by ajantha-bhat** [comment]
PR just got merged. (https://github.com/trinodb/trino/pull/11701)

The upcoming Trino 419 version will ship with the nessie support.

**Comment by ajantha-bhat** [comment]
Hello @code-magician323, @jebnix ,  @almogtavor,  @rbreejen, @EternalDeiwos

As Nessie is integrated with Trino, only the basic configurations are provided to reduce the review effort. 
Now in a follow up PR, we are supporting additional configurations like Auth https://github.com/trinodb/trino/pull/17725

In the production, Nessie will likely be deployed with Auth. Hence, it is much needed. 

It seems we need to show the community demand for this for active review. 
So, can you please go and comment on the PR if it is really useful for you guys? Thanks.
