### ISSUE TITLE
REST API v2: expose additional parents

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#5634]
PR #4333 allowed to store and retrieve the head of a merge-source. At that time, it was not possible to expose the additional parents in the API (CommitMeta) due to backwards compatibility constraints. The workaround was to add `CommitMeta.MERGE_PARENT_PROPERTY` as a generic property.

With REST API v2 however, we can safely add a new field `List<Hash> additionalParents` to `CommitMeta` and only return it, when the request was received as v2.

This issue is to add the new field for REST API v2, and remove the `CommitMeta.MERGE_PARENT_PROPERTY` hack for v2.

**Comment by dimas-b** [comment]
Parent hashes were added to `CommitMeta` in API v2 under #5424

**Comment by snazy** [comment]
Looks like this has been fixed via #5706
