### ISSUE TITLE
Named references should only contain valid characters

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#578]
As briefly mentioned in #395, it's beneficial to add some validation of reference-names (aka branch/tag names).

Git basically limits ref-names to what file/path names allow plus some more restrictions:
* only ASCII chacaters, 8 bit (no äöüß for germans for example)
* mustn't begin with a `.`
* must not contain `..`
* no ASCII control characters
* must not contain `?`, `:`, `[`, `\`, `^`, `~`, space, tab
* must not end with a `/`
* must not end with `.lock`
* must not contain `@{`

I think, that's mostly due to git using a file-system underneath and/or many operations should be mapable to a file-system.
In Nessie, we're not actually restricted by file-system semantics.

We could do what git does, but extend the set of valid characters to what Java allows for identifiers.

Thoughts?

**Comment by jacques-n** [comment]
It is much easier to add characters than to remove them. I suggest we go very limited for now.

Characters: [A-Za-z][A-Za-z0-9./-_]*

Plus all the further constraining git rules.
- must not contain ..
- must not end with a /
- must not contain @{
