### ISSUE TITLE
Add content ID to `EntriesResponse` in API v2

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5878]
Content ID can be used to distinguish entities with the same name (same key) in different commits (branches, tags).

Having content ID in `EntriesResponse` can help to avoid an extra call to the `getContent` API.

**Comment by snazy** [comment]
Looks like this is a rather simple change, meaning the only change's needed in the REST API v2 and its TreeApiImpl. `org.projectnessie.versioned.KeyEntry` already contains the content-ID.
