### ISSUE TITLE
Update CLI to match Git syntax

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#60]

**Comment by jacques-n** [comment]
Initial plan here: 
https://gist.github.com/laurentgo/e762c7258ae1176b887ce9a76f8ab394

Need to also add merge, cherry-pick, rebse, path listing (assume that exists in git)

**Comment by rymurr** [comment]
2nd draft
https://gist.github.com/rymurr/83ef4129d37e92907e53f68bd893ce2e

@laurentgo @jacques-n what do you think
