### ISSUE TITLE
Reduce the size of l1 to make InternalBranch, etc typically fit under 1K

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#602]
This requires adjusting the amount of items in the l1 tree as well as reducing the parents count so that we hit this number. We should do this before 0.3

**Comment by jacques-n** [comment]
@rymurr let me know if you have some time to look at this today. If not, I'll take a look at it.

**Comment by jacques-n** [comment]
Note, this is a non-backwards compatible metadata storage change. I think we should skip building a migration operation at this point.

**Comment by rymurr** [comment]
looking now

**Comment by rymurr** [comment]
The breakdown of the L1 object:
id = 20 bytes
metadata = 20 bytes
type = 2 bytes
id map = n * 20 bytes
parent list = m * 20 bytes
key list = potentially large but only  when adding/changing many tables in 1 transaction or single tables w/ large names.

for now I am ignoring the key list.

Current L1 has n=151 and m=50 giving a size of 4056 or  38 bytes short of the 4k limit
Reducing L1 to n=36 and m=10 gives a size of  956 bytes or 68 bytes short of the 1k limit

The minimum size of the key list is 25 bytes which leaves 37 bytes for a table name. "testing.nation" is already 16 bytes and I expect in practice much larger table names so while n=36 seems small I think it gives enough overhead to support the KeyList in L1.

However, we are really trying to ensure that the refs table is able to mutate at a high rate. The Ref table is sized rather differently:
id = 20 bytes
metadata = 20 bytes
type = 2 bytes
name = name length * 1 byte (assuming lower end of UTF-8 encoding)
tree = n * 20 bytes
commits = 3*20 per commit with unknown number of commits (depending on when L1 last commited)

Size = 120+20*n (assuming 20 character branch name for this purpose)
This could support n=45 and the table size would be 1020 bytes or using 36 from above 840 bytes

I have raised #607 to implement n=36 and to reduce the parent list. We can discuss if that is the right number.
