### ISSUE TITLE
Nessie native image for arm64

### ISSUE THREAD

**Issue by tmnd1991** [projectnessie/nessie#6094]
**Description**:
Right now nessie docker image is published only for amd64 architecture. 
It would be good to publish the image also for arm64.

**Requested Changes in public API**:
- ❌Changes in REST API
- ❌Changes in Java Client API
- ❌Changes in Python Client API
- ❌Changes in SQL extentions
- ✅Changes in build/publish

**Expected Use Cases**:
Run Nessie natively on arm64 machines.

**Comment by tmnd1991** [comment]
I dig a bit in the build and I understood that Nessie is using `jib` to build the container image.

[quarkus.jib.platforms](https://quarkus.io/guides/container-image#quarkus-container-image-jib_quarkus.jib.platforms) could be used to set the arm64 architecture, but unfortunately the "multi" platform feature of jib does not work for native image, so unfortunately two different steps/workflows would be needed to make it work.

Would you accept a PR on this?

**Comment by dimas-b** [comment]
Thanks for the PR :eye:

**Comment by snazy** [comment]
Closed after discussion in and in favor of #6099

**Comment by snazy** [comment]
Closed after discussion in and in favor of #6099 / #6110

**Comment by snazy** [comment]
Oh, and what I haven't really realized before: GitHub offers only offers runners on x86_64, none for amd64/aarch64. In other words, we'd have had no chance to build the amd64/aarch64 native binaries in CI :(

**Comment by tmnd1991** [comment]
Yeah, that sucks :( you probably need custom runners to do so. I know the guys at typelevel managed to have them, but never investigated how
