### ISSUE TITLE
Docker image - native vs "pure Java"

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6099]
The issues #6094 / #6098 brought up the request to add arm64 (v8?) Docker images in addition to those for x86/64.

Technical side node: Additional native images are actually hard to maintain and impose quite some testing effort - at least in CI. This can be however neglected, it just requires another job in the 4 affected workflows running on the "right" runner.

A technical limitation, because we're using OSS GraalVM to generate native images, is that those native binaries only support the "good old Serial GC" (think: long running, stop-the-world GC), which can block for a couple of seconds, especially when heap pressure is high / lots of objects generated. The plus side of native images however is the extremely fast startup time.

"Pure Java" images have a longer startup time, but perform (at least in my experience) generally better, especially when running for a longer period of time. It's technically a "vanilla" Java 11 or 17 VM. Jib can also build "pure Java" images for [multiple platforms](https://quarkus.io/guides/container-image#quarkus-container-image-jib_quarkus.jib.platforms) in a single build.

Opinions?

**Comment by dimas-b** [comment]
Given the GC argument above, I feel like dropping native images. Fast startup is nice, but Nessie servers are generally expected to run for long periods, I suppose, so GC matters more, IMHO.

**Comment by snazy** [comment]
@tmnd1991 what's your opinion on "pure Java vs native"? Do you guys run Nessie more "lambda-ish" or as "long running" instances?

**Comment by tmnd1991** [comment]
Hi guys, the deployments I've witnessed are all "long running" deployments on kubernetes, so replacing native publishing in favor of pure java is definitely a good idea.
I would keep testing and building native nessie in order to be future-proof and be able to switch back at some point

**Comment by snazy** [comment]
Sounds good :) And yea, there's no plan to "nuke" native images entirely.

The only downside is that I can't get Quarkus multiplatform builds to [work correctly](https://github.com/quarkusio/quarkus/issues/31191). So, it may take a little time.
