### ISSUE TITLE
Typescript: /v2/trees/{ref} Response nested inside of an object

### ISSUE THREAD

**Issue by swillis12** [projectnessie/nessie#6210]
**What happened**: GET /v2/trees/{ref} returns
```
{
   "reference":{
      "type":"BRANCH",
      "name":"main",
      "hash":"b5f61965b8822063ab67259a6edb7c1eb2a0d739a92aebac338feec7d4039e6f"
   }
}
```
Note: The same issue occurs for POST of the same URL (Creating a reference), the return value has the same nesting.

**What you expected to happen**:
Response should be as defined in the [Swagger definition](https://app.swaggerhub.com/apis/projectnessie/nessie/0.48.2#/v2-beta/getReferenceByNameV2):

```
{
  "type": "BRANCH",
  "hash": "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d",
  "name": "main"
}
```

**How to reproduce it (as minimally and precisely as possible)**: Make a call to GET /v2/trees/-

**Details**:
- Nessie server type (docker/built from source) and version: Using 0.48.2 and confirmed the same behavior in 0.50.0
- Client type (Ex: UI/Spark/pynessie ...) and version: Browser

**Comment by snazy** [comment]
The response is correct - the open-api spec is wrong here.
