### ISSUE TITLE
queryParam 'type' in DELETE /v2/trees/{ref} is nonnull while the swagger says it is optional.

### ISSUE THREAD

**Issue by leewjae** [projectnessie/nessie#6223]
According to the Swagger API, the type param should be optional for DELETE /v2/trees/{ref} , but in actual implementation in Util.java, it forces to have non null value. Can I get some clarification on this? Thanks!
![Screen Shot 2023-03-04 at 3 33 43 PM](https://user-images.githubusercontent.com/38933452/222936714-6431164d-16b1-466e-a39f-8daf09920af3.png)
![Screen Shot 2023-03-04 at 3 33 31 PM](https://user-images.githubusercontent.com/38933452/222936715-1b682160-5c22-46bc-b813-adc21f65d1fc.png)

**Comment by snazy** [comment]
This is probably an oversight in V2. In V1, the reference-type was implicitly mandatory as part of the path. In V2 it is (should be) indeed optional.
