### ISSUE TITLE
Verify Nessie docs in Iceberg are correct

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6255]
The Nessie version number(s) and Maven group ID (changed to `org.projectnessie.nessie`) in the Iceberg docs (e.g. https://iceberg.apache.org/docs/latest/nessie/) are outdated and (now) incorrect.

This issue is to track this effort on the Nessie side.

**Comment by ajantha-bhat** [comment]
@snazy:

a) Should this be done with/after 0.51.1 bump? Is anyone working on 0.51.1 bump or I can do that too? 
b) Note that  I can only modify group id in https://github.com/apache/iceberg/blob/master/docs/nessie.md but the Nessie version has to be updated by release owner in iceberg-docs like [this](https://github.com/apache/iceberg-docs/commit/65221f25d792698636374ba1e42e5385f8be83fd)

**Comment by ajantha-bhat** [comment]
oops, I see that 0.51.1 was already merged. So, I missed it. I will update these documents.

**Comment by ajantha-bhat** [comment]
fixed by: https://github.com/apache/iceberg/pull/7060
