### ISSUE TITLE
Move away from Docker Hub

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6293]
Docker terminates all free plans soon.

Current options:
* Github registry
* quay.io

Both options are free to use. Maybe we should just publish to both, but only "advertise" one of those in the Readme.

Migration can be easily done using the [regctl](https://github.com/regclient/regclient) tool  - just need "some" network bandwidth to actually copy the images around.

Either each image individually using `regctl image copy <source_image:tag> <target_image:tag>` or, probably much easier, via [`regsync`](https://github.com/regclient/regclient#regsync-features).

Should also update:
* Docker badge in the `README.md`
* Links on the website

**Comment by snazy** [comment]
Note: ghcr.io does not seem to support TLS 1.3 properly:
```
$ curl -v https://gchr.io/v2/projectnessie/nessie-binder-demos/manifests/649ec80b8fa7d9666178380a33b2e645a52d5985 
*   Trying 81.171.22.4:443...
* Connected to gchr.io (81.171.22.4) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:0A000410:SSL routines::sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:0A000410:SSL routines::sslv3 alert handshake failure
```

**Comment by adutra** [comment]
For completeness sake, Docker is not terminating all free plans, only the Free Team plan.

As individuals collaborating on an OSS project like Nessie, we are entitled to use the Personal subscription plan. From [this FAQ](https://www.docker.com/pricing/faq/):

> Docker Desktop may be used for free as part of a Docker Personal subscription for [...] Non-commercial open source projects

Moreover, a program called Docker-Sponsored Open Source Program (DSOS) exists. From [this page](https://www.docker.com/community/open-source/application/):

> To qualify for the program, your project must:
> * Be shared in public repos.
> * Meet the [Open Source Initiative definition](https://opensource.org/docs/osd)
> * Be in active development [...]
> * Not have a pathway to commercialization

And also:

> * Program members, and all users pulling public images from your project namespace, get access to unlimited pulls and unlimited egress.
> * Core contributors of your project namespace get access to a year-long Docker Team subscription which includes: Docker Desktop, 15 concurrent builds, unlimited Docker Hub image vulnerability scans, unlimited scoped tokens, role-based access control, and audit logs.

I think Nessie could meet the above requirements, and therefore could apply to DSOS and continue publishing to Docker Hub.

This, of course, doesn't preclude investigating ways to _also_ deploy to other hubs such as quay.io or ghcr.io.

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits to other registries.

There are also features regarding containerized image distribution to other registries or to your customers if you have a commercial project.
