### ISSUE TITLE
Add tests to cover hash collisions in L1s/L2s

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#631]
As per #607 we should add some tests to cover all TieredVersionStore operations when there are multiple commits that end up in the same L1 or L2 stripe. This will prevent errors like we saw in #607 and further test the version store.

Some possible test routes:
1) make the L1, L2, L3 size configurable at start up via a system property and run the integration test suite for with very small sizes
2) find a list of partial SHA256 hash collisions so that commits are forced to overlap

**Comment by rymurr** [comment]
https://stackoverflow.com/questions/60701952/sha256-find-partial-collision is a good starting point for 2. Should be easy to construct a birthday attack that quickly finds an overlap of 4 and 8 digits for L1 and L2 overlaps respectively

**Comment by snazy** [comment]
Superseded by #1638
