### ISSUE TITLE
Update soft-assertions in Quarkus tests, once Quarkus allows that

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6400]
## Soft-assertions should work fine in Quarkus 3

The following construct, used in a few test classes, can then be replaced with the softly JUnit extension.

```
  // Cannot use @ExtendWith(SoftAssertionsExtension.class) + @InjectSoftAssertions here, because
  // of Quarkus class loading issues. See https://github.com/quarkusio/quarkus/issues/19814
  protected final SoftAssertions soft = new SoftAssertions();

  @AfterEach
  public void afterEachAssert() {
    soft.assertAll();
  }
```

**Comment by adutra** [comment]
The following construct is found in many build scripts where Keycloak testcontainers is used:

```kotlin
  intTestImplementation(libs.testcontainers.keycloak) {
    exclude(group = "org.slf4j") // uses SLF4J 2.x, we are not ready yet
  }
```

The exclusion should be removed once in Quarkus 3.

**Comment by snazy** [comment]
Reduce Gradle heap size from 3g back to 2g (bumped via #7151)

**Comment by snazy** [comment]
Using the soft-assertion-extension in tests running via Quarkus will possibly never work - a class-loader issue in combination with serialization at play here
