### ISSUE TITLE
Docs update in Spark Via Iceberg

### ISSUE THREAD

**Issue by jacopotagliabue** [projectnessie/nessie#6417]
The page https://projectnessie.org/tools/iceberg/spark/ reports an incorrect apache iceberg version for `org.projectnessie.nessie-integrations:nessie-spark-extensions-3.3_2.12:0.53.1`. 

The correct one should be: `https://central.sonatype.com/artifact/org.apache.iceberg/iceberg-spark-runtime-3.3_2.13/1.2.0/overview`

**Comment by ajantha-bhat** [comment]
@jacopotagliabue: Thanks for reporting. 

I have raised a PR to fix it.  
https://github.com/projectnessie/nessie/pull/6419
