### ISSUE TITLE
Configure the model option (old versus new model) in OlderNessieServersExtension annotation

### ISSUE THREAD

**Issue by mthirani2021** [projectnessie/nessie#6473]
**Description**:
Would like to configure the model option in OlderNessieServersExtension annotation so that maven-failsafe-plugin is able to spin up the Nessie server with the correct model option instead of running the integration tests using verify for the new model where we have to run the OSS Nessie via maven apprunner plugin, which makes it harder to run/ debug tests in local.

For e.g:
mvn failsafe:integration-test  -pl :sample-model -Dit.test=ITSampleTest

**Requested Changes in public API**:
- Changes in REST API
- Changes in Java Client API
- Changes in Python Client API
- Changes in SQL extentions

**Expected Use Cases**:
To be able to spin up the Nessie server with new model using the OlderNessieServersExtension, so that failsafe-plugin can be used in Integration tests framework. This will allow us to debug/ run the specific test

**Comment by mthirani2021** [comment]
@dimas-b FYI

**Comment by snazy** [comment]
Why and what are all these requested changes if it's a test-code-only issue?

**Comment by dimas-b** [comment]
I think the basic idea is to be able to run tests with `OlderNessieServersExtension` that run with the new Nessie data model.
