### ISSUE TITLE
Namespace Enforcement in Nessie Server 0.56 even option was passed as false

### ISSUE THREAD

**Issue by mthirani2021** [projectnessie/nessie#6544]
While trying to spin up the OSS Nessie Server 0.56 without namespace enforcement, it still tries to validate the namespaces and do not create Implicit folders.

**What happened**:
Getting the below error while trying to create an implicit folder where OSS Nessie server is spinned up based on no namespace enforcement check.

Command used for spinning up OSS Nessie:

`docker run -e NESSIE_VERSION_STORE_ADVANCED_VALIDATE_NAMESPACES=false -p 19120:19120 --rm projectnessie/nessie:0.56.0`

![image](https://user-images.githubusercontent.com/96448504/230737274-a3d4f351-37bd-45e7-8163-4ca23ae205a5.png)

**What you expected to happen**:

It should have created the implicit folders without no namespace enforcement

**How to reproduce it (as minimally and precisely as possible)**:

Spin up the OSS Nessie server using the docker command:

`docker run -e NESSIE_VERSION_STORE_ADVANCED_VALIDATE_NAMESPACES=false -p 19120:19120 --rm projectnessie/nessie:0.56.0`

Try to do commit using implicit folder

**Details**:
- Nessie server type (docker/built from source) and version: 0.56.0
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by mthirani2021** [comment]
@dimas-b FYI

**Comment by dimas-b** [comment]
@mthirani2021 : the docker image runs with the new in-memory data model by default. The option name is different in this case. It is `-e NESSIE_VERSION_STORE_PERSIST_NAMESPACE_VALIDATION=false`

**Comment by dimas-b** [comment]
Just to clarify, the `NESSIE_VERSION_STORE_ADVANCED_VALIDATE_NAMESPACES` env. var. applies to the old model.

Here's how to run Nessie with the old in-memory model and without namespace validation: `-e NESSIE_VERSION_STORE_TYPE=INMEMORY -e NESSIE_VERSION_STORE_ADVANCED_VALIDATE_NAMESPACES=true`

**Comment by mthirani2021** [comment]
That seems working. Thanks!

**Comment by mthirani2021** [comment]
Working with `-e NESSIE_VERSION_STORE_PERSIST_NAMESPACE_VALIDATION=false` for newer model.

While trying to use older model with no enforce in namespace validation, it seems the same issue though. 

`docker run -e NESSIE_VERSION_STORE_TYPE=INMEMORY -e NESSIE_VERSION_STORE_ADVANCED_VALIDATE_NAMESPACES=true -p 19120:19120 --rm projectnessie/nessie:0.56.0`
