### ISSUE TITLE
`GET /config` on a v1 base URL should return `maxSupportedApiVersion` of `1`

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#6585]
If a client is unaware of the server-side Nessie API version, it needs to be able to validate the API level supported under the base Nessie REST URL it was provided.

For example, if a client is compiled to Nessie API v2, it needs to be able to validate whether API v2 is available under the base URL.

**Comment by snazy** [comment]
Well, that config value says that the _max supported_ API version is X, so `2` is the (currently) correct one.

**Comment by dimas-b** [comment]
yes, but clients cannot switch base URLs :thinking:

**Comment by snazy** [comment]
That is why there is `org.projectnessie.model.NessieConfiguration#getSpecVersion` that's returned for the V2 endpoint.
It has been introduced for exactly this reason.

**Comment by dimas-b** [comment]
I stand corrected. Closing.
