### ISSUE TITLE
`NessieApi.close()` method might not be called by Iceberg

### ISSUE THREAD

**Issue by adutra** [projectnessie/nessie#6586]
Iceberg's `Catalog` does not extend `(Auto)Closeable`, even if some `Catalog` implementations do (e.g. `NessieCatalog` or `RESTCatalog`).

`NessieApi` implements `AutoCloseable`, and since recent changes from #6527, not calling its `close()` method could leak resources. The problem happens for now when using the new `OAuth2AuthenticationProvider`.

We need to figure out how to properly close Nessie client's resources when used as a catalog for Iceberg, even if its `close()` method is not called. Maybe with a shutdown hook or some idle detection mechanism.

**Comment by snazy** [comment]
For posterity: There's probably no way, especially in Spark, to know whether an Iceberg catalog instance is still being used or not (Spark does not have a proper resource management wrt catalogs - there's nothing like a `Catalog.close()`).

What we could potentially do is to let our `org.projectnessie.client.auth.oauth2.OAuth2Client` stop the executor needed for token refresh when the client hasn't been used for some time - and restart it if it is being used again, which likely requires a full-authentication round-trip. That's not perfect, but better than leaving threads and resources around.

**Comment by snazy** [comment]
Leaving this one open until we have a mechanism for `NessieApi.close()` as well.

**Comment by snazy** [comment]
Not sure whether it's worth to investigate this one further, given the direction towards Iceberg REST
