### ISSUE TITLE
Helm Chart: Add option to get MongoDB Connection String from Secret

### ISSUE THREAD

**Issue by c-thiel** [projectnessie/nessie#6670]
Currently when using a MongoDB as a backend, only Username and Password can be specified as a secrets.
However, MongoDB supports many different authentication options, not only Username and Password - and QUARKUS does as well.

For the specific case of MongoDB it would be great to add the option to get the `QUARKUS_MONGODB_CONNECTION_STRING` from a secret instead of from the values directly.

Additionally, it would be great to add a general `extraEnv` section to the values.yaml, that allows users to use additional configuration options of QUARKUS for different databases, even when they are not explicitly supported in the chart.

**Comment by c-thiel** [comment]
I don't, but I can create one this week :)

**Comment by adutra** [comment]
Hi @c-thiel, thanks for reporting this!

Regarding this:

> Additionally, it would be great to add a general extraEnv section to the values.yaml, that allows users to use additional configuration options of QUARKUS for different databases, even when they are not explicitly supported in the chart.

Have you noticed that we introduced an `advancedConfig` section in the value.yaml file recently? You can use it to pass any Quarkus or Nessie configuration property, e.g.:

```yaml
advancedConfig:
  quarkus.mongodb.connect-timeout: PT5S
  quarkus.mongodb.max-connection-idle-time: PT60S
```

Does that help?

**Comment by c-thiel** [comment]
Hi @adutra,
unfortunatley it doesn't as it allow to get the value from a secret. We can just hard-code it in the values.yaml where secrets don't belong ;)

**Comment by c-thiel** [comment]
I opted to only add extraEnv instead of a specific QUARKUS_MONGODB_CONNECTION_STRING solution. While this is a bit more complicated to use, it fixes the secret issue for any other field as well.
