### ISSUE TITLE
Refactor CommitImpl#contentIdFromContent to pre-load contents

### ISSUE THREAD

**Issue by adutra** [projectnessie/nessie#6673]
See https://github.com/projectnessie/nessie/pull/6647#discussion_r1173790811 for context.

Refactor `org.projectnessie.versioned.storage.versionstore.CommitImpl#contentIdFromContent` to pre-load these contents, so they are bulk-loaded and in turn available via the cache.

**Comment by snazy** [comment]
Looked a bit more into this, and I thing that the probability of that function being called is effectively 0, so it is not worth the effort.
