### ISSUE TITLE
Events & model types

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#6820]
Currently the events object model mirrors all (built in) content types from `:nessie-model` 1:1 in ':nessie-events-api`.

This issue is to think about whether it's better to do this or whether it's "enough" or maybe better (think: custom types) to handle all content types generically in the Nessie events code.

Pro "generic content" in events:
* less code
* content is "just passed through", not handled on a case-by-case bases
* feels more future proof - thinking of whether there could be differences in serialization between a "well known" and generic type - or type clashes in 3rd party event-SPI implementations.

**Comment by adutra** [comment]
Yes I agree, this would simplify things a lot. And we wouldn't need that common content module anymore. +1 for implementing that (will do asap).

**Comment by dimas-b** [comment]
Now that we have fallback parsers for unknown (pluggable) content types, reusing them for events makes sense to me.
