### ISSUE TITLE
Update Mongo PROPERTY_PRODUCERS to use ImmutableMap

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#692]
Right now, the static maps for the MongoBaseValue objects use a mutable hashmap. We should build an immutable map within a single static invocation.

**Comment by jacques-n** [comment]
Missed some places such as 
https://github.com/projectnessie/nessie/blob/main/versioned/tiered/mongodb/src/main/java/com/dremio/nessie/versioned/store/mongodb/MongoFragment.java#L33

Also, I'd suggest you use a chained construction rather than having the declaration and a separate static initialization block. Generally feels cleaner.

**Comment by snazy** [comment]
Oh, that specific one (these property-maps) are going away with the latest commit to #700.

**Comment by snazy** [comment]
Fixed via #691 and others
