### ISSUE TITLE
Enabling withEnableApiCompatibilityCheck to true does not enforces v2 in URL

### ISSUE THREAD

**Issue by mthirani2021** [projectnessie/nessie#6946]
While trying to create the NessieApiV2 object with the nessie endpoint - http://localhost:19120/api/v1 and enabling the param 
`withEnableApiCompatibilityCheck` to `true`, I can create the object successfully with no issues but was expecting that it should throw error instead.

**What happened**:
Tried to enable the compatibility parameter `withEnableApiCompatibilityCheck` to make sure v1 is not part of URL and it throws error instead while building the NessieApiV2 instance.

**What you expected to happen**:
Throwing an error for the invalid url

**How to reproduce it (as minimally and precisely as possible)**:
Spin up the latest OSS Nessie and pass the URL as http://localhost:19120/api/v1 and try to create the NessieApiV2 instance using below:
```
HttpClientBuilder.builder()
        .withUri(URI.create(nessieEndpoint));
        .withEnableApiCompatibilityCheck(true)
        .build(NessieApiV2.class);
```

**Details**:
- Nessie server type (docker/built from source) and version: 0.60.1
- Client type (Ex: UI/Spark/pynessie ...) and version:

**Comment by adutra** [comment]
Hi @mthirani2021 in #6893 we decided to defer the check to the first request made with the client. This is maybe the reason why you are not seeing any error right away.

**Comment by mthirani2021** [comment]
@adutra hopefully I can use it in next published version then. right?

**Comment by adutra** [comment]
@mthirani2021 yes it will ship in 0.61.0.
