### ISSUE TITLE
Best Practices for MongoDB Sharding

### ISSUE THREAD

**Issue by c-thiel** [projectnessie/nessie#6981]
We are currently using MongoDB as a backend for Nessie and expect a large environment in the future.
What I am missing is some guidance on how to shard the MongoDB Collections.

Is there some experience already somewhere on this? This would also be some valuable information for the configuration documentation.

**Comment by dimas-b** [comment]
@c-thiel : Do you use the new model, i.e. `MONGODB` store type (hopefully), or the old model, i.e. `MONGO`?

**Comment by dimas-b** [comment]
As for the new model, I do not really have any numbers at this time, but I'd suggest to try and shard like this (based on code behaviour):

`objs` : `_id.r` and `_id.i` (full composite PK)
`refs` : `_id.r` (repository ID)

**Comment by c-thiel** [comment]
Thanks for the insights @dimas-b. We are using the new Model.
I will give it a shot :)

From my Side we could close this issue. Or do you prefer to keep it open to track maybe documentation?
