### ISSUE TITLE
Several issues and bugs with nessie-gc CLI tool

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7401]
While trying to set up a maintenance workflow for our Nessie-backed Iceberg tables, I ran into several issues with the nessie-gc CLI utility. These unfortunately make it rather unusable to us right now.

**What happened**:

There were four separate issues I encountered:
 1. This is more of a usability thing, but when using JDBC for storing the live set data, I wanted to specify all the required configuration via environment variables, but when not specifying at least one of them as command line argument, I get the error `Error: Missing required argument (specify one of these): ([--inmemory] | [[--jdbc-url=<url>] [--jdbc-properties[=<String=String>[,<String=String>...]...]]... [[--jdbc-user=<user>] [--jdbc-password=<password>]]])`. This is easy enough to work around, but still a little annoying
 2. The log level appears to be `DEBUG` regardless of the value of the `log.level.console` system property
 3. When running the identify-live-content phase of the GC, after it's done listing all live references, I get an error from the backing Postgres database with message `ERROR: duplicate key value violates unique constraint "gc_live_set_contents_pkey"`. The culprit appears to be the [`collectAllKeys`](https://github.com/projectnessie/nessie/blob/main/gc/gc-base/src/main/java/org/projectnessie/gc/identify/IdentifyLiveContents.java#L337-L346) method.
 4. Trying to run the sweep operation against Iceberg tables on S3, I get a `java.lang.ClassNotFoundException: software.amazon.awssdk.services.sts.model.Tag`

**What you expected to happen**:
 1. The command line arguments for the JDBC storage should not be required if provided via environment variables
 2. The default log level should be `INFO` and the `log.level.console` system property should properly change it
 3. The identify-live-content phase should run with Postgres backing storage without any primary key constraint violations
 4. The sweep phase should run against S3-backed Iceberg tables without a hitch with the distributed version of the CLI

**How to reproduce it (as minimally and precisely as possible)**:
For the separate issues, this is assuming a Postgres database at `localhost:5432` with the nessie-gc tables set up in the `nessie_gc` database as well as a Nessie server running at `localhost:19120`.

I was able to generate a live content set from the source version of the CLI by adding `ON CONFLICT DO NOTHING` to the following query:
https://github.com/projectnessie/nessie/blob/95bb6ccd59a80266d87183d930b4ee92815ec998/gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/SqlDmlDdl.java#L158-L161

This is how to reproduce the issues with this setup:
 1. Run `NESSIE_GC_JDBC_URL="jdbc:postgresql://localhost:5432/nessie_gc" NESSIE_GC_JDBC_USER=postgres NESSIE_GC_JDBC_PASSWORD=pass nessie-gc list` and observe the error message.
 2. Run `nessie-gc gc --inmemory` and observe debug-level messages like `Checking commit <hash> ...`
 3. Run `NESSIE_GC_JDBC_URL="jdbc:postgresql://localhost:5432/nessie_gc" NESSIE_GC_JDBC_USER=postgres NESSIE_GC_JDBC_PASSWORD=pass nessie-gc mark --jdbc-user=postgres` and observe the error message after a lot of debug messages for checking individual commits
 4. Run `nessie-gc sweep --defer-deletes` with S3 Hadoop and Iceberg configurations against a live set and observe the error message

**Details**:
- Nessie server type (docker/built from source) and version: Docker (on Kubernetes) v0.65.0
- Client type (Ex: UI/Spark/pynessie ...) and version: nessie-gc CLI v0.67.0

For the second issue with the log levels, it appears the following line is at fault:
https://github.com/projectnessie/nessie/blob/95bb6ccd59a80266d87183d930b4ee92815ec998/gc/gc-tool/src/main/resources/logback.xml#L27
Removing the escaping backslash in front of the dollar sign, I get correct INFO-only output and the CLI respects the `log.level.console` system property.

**Comment by XN137** [comment]
thanks for reporting back on these issues but i wonder if filing separate issues would be beneficial for tracking them (unless they are strongly related i.e. same cause)

if you think there is an easy solution to some of them, feel free to provide a PR

problem 4 has already an (unreleased) fix [here](https://github.com/projectnessie/nessie/pull/7385)

there is a discussion on zulip about it [here](https://project-nessie.zulipchat.com/#narrow/stream/371187-general/topic/Nessie.20GC)

a workaround for that might be to use the gc tool like this:
```
wget https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.20.99/bundle-2.20.99.jar
wget https://repo1.maven.org/maven2/software/amazon/awssdk/url-connection-client/2.20.99/url-connection-client-2.20.99.jar
java -cp 'bundle-2.20.99.jar:url-connection-client-2.20.99.jar' -jar nessie-gc-0.67.0 gc --uri=http://localhost:19120/api/v2 --inmemory --iceberg s3.access-key-id=$AWS_ACCESS_KEY_ID,s3.secret-access-key=$AWS_SECRET_ACCESS_KEY
```

**Comment by marvin-roesch** [comment]
I can definitely create separate issues for these, I wanted to get these laid out first to see if there was anything I was doing obviously wrong.

Good to know there's already a fix for the S3 issue, we can also do the workaround for the time being until there's a new release!

For the log level issue, I will definitely prepare a pull request, as that's a simple enough fix. The key violation issue I feel less confident about, as I do not know enough about the GC, so maybe there's something else going wrong that it even tries to add these rows to the database table?

I'll create the separate issues now and will close this one!
