### ISSUE TITLE
nessie-gc: Some JDBC command line argument is still required even if it's fully configured via environment variables

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7405]
When using the JDBC capability of nessie-gc (e.g. with Postgres), the CLI appears to not be "clever enough" to get fully configured by present environment variables and instead requires one of the CLI arguments to still be specified.

**What happened**:
Running any command that requires a database connection with `NESSIE_GC_JDBC_*` options in the current environment but without any of the `--jdbc-*` command line arguments, I get the following error message:

```
Error: Missing required argument (specify one of these): ([--inmemory] | [[--jdbc-url=<url>] [--jdbc-properties[=<String=String>[,<String=String>...]...]]... [[--jdbc-user=<user>] [--jdbc-password=<password>]]])
```

**What you expected to happen**:
I expected nessie-gc to get fully configured through the environment variables such that the command line arguments are not necessary anymore.

**How to reproduce it (as minimally and precisely as possible)**:
With a Postgres database running at `localhost:5432`, run the following command:
```bash
NESSIE_GC_JDBC_URL="jdbc:postgresql://localhost:5432/nessie_gc" NESSIE_GC_JDBC_USER=postgres NESSIE_GC_JDBC_PASSWORD=pass nessie-gc list
```
Observe the error message shown above.

**Details**:
- Nessie server type (docker/built from source) and version: Docker (on Kubernetes) v0.65.0
- Client type (Ex: UI/Spark/pynessie ...) and version: nessie-gc CLI v0.67.0

**Comment by marvin-roesch** [comment]
@snazy It looks like your changes unfortunately were not actually sufficient to fully fix this issue. When I'm trying to execute a command like the one outlined in the issue with version 0.68.0 but with the `--jdbc` option, I get an error like `SCRAM authentication failed` because it attempts to connect to the database using my local system user.

It appears that picocli will not instantiate and populate an `@ArgGroup`-annotated field with default values unless one of the options in that group is explicitly specified. So the `UsernamePassword` field is `null` even if `NESSIE_GC_JDBC_USER` and `NESSIE_GC_JDBC_PASSWORD` are set in the environment.

An easy fix would be to pull the username and password options into `JdbcOptions` directly. What do you think of that? This has the added advantage that a password is not actually required by Postgres if the user does not have a password set, while nessie-gc right now requires a password to be specified if a user is (and vice-versa, of course).

I locally tested this change and it works fine. An unfortunate side-effect however is that it allows an "illegal" argument combination of specifying a password but not a user.

**Comment by snazy** [comment]
Indeed, that doesn't sound nice. Let me see what I can do.
