### ISSUE TITLE
nessie-gc: Running mark phase against Postgres database results in duplicate rows

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7408]
When running the `nessie-gc mark` command with a Postgres database as backing storage, the operation can fail due to duplicate rows in the `gc_live_set_contents` table.

**What happened**:
After attempting to run the mark phase, an error like the following occurs (only the last exception listed as that is the root cause):
```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "gc_live_set_contents_pkey"
  Detail: Key (live_set_id, content_id, commit_id)=(f8248937-1066-46c4-af57-c507df37398d, 201c5e9c-a664-43c3-8f42-e192969e6d80, 8c0bd90ff3f4cbb9cdafbcd368715e566bdfb33004f3d1fe0b4481b44fb0bc13) already exists.
```

**What you expected to happen**:
The mark phase should run through without issue.

**How to reproduce it (as minimally and precisely as possible)**:
With a Postgres database running at `localhost:5432`, run the following command and observe the error message after a lot of debug messages for checking individual commits:
```
NESSIE_GC_JDBC_URL="jdbc:postgresql://localhost:5432/nessie_gc" NESSIE_GC_JDBC_USER=postgres NESSIE_GC_JDBC_PASSWORD=pass nessie-gc mark --jdbc-user=postgres
```

**Details**:
- Nessie server type (docker/built from source) and version: Docker (on Kubernetes) v0.65.0
- Client type (Ex: UI/Spark/pynessie ...) and version: nessie-gc CLI v0.67.0

I already looked into this a little myself with the current source of nessie-gc. It looks like the issue is in the `collectAllKeys` method:
https://github.com/projectnessie/nessie/blob/b3b28033285c210bdbb2879c0944630ae8e99ab1/gc/gc-base/src/main/java/org/projectnessie/gc/identify/IdentifyLiveContents.java#L337-L346

So the iteration of all live references goes through smoothly, but once the first non-live commit is reached, this causes several (all?) commits to be added to the live set again.

In order to ensure there weren't any other issues, I added `ON CONFLICT DO NOTHING` to the query responsible for this:
https://github.com/projectnessie/nessie/blob/95bb6ccd59a80266d87183d930b4ee92815ec998/gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/SqlDmlDdl.java#L158-L161
The mark phase ran through in its entirety, but I am not at all confident in the results this generated. I'm not familiar enough with the GC to judge whether this "fix" is somehow right or should even be necessary.

**Comment by snazy** [comment]
Thanks for reporting this one!

It's intentional, that duplicate `ContentReference` can be passed to `PersistenceSpi.addIdentifiedLiveContent`. There is already a check using `isIntegrityConstraintViolation()` to not "bark", when a duplicate key's inserted, so your workaround wasn't wrong - it should have been not necessary.

I'll take a look into it.

**Comment by marvin-roesch** [comment]
Thanks for the quick fix on this one!
