### ISSUE TITLE
about presto for nessie

### ISSUE THREAD

**Issue by laopeng2021** [projectnessie/nessie#743]
Hi, look at the information, nessie supports spark and dremio queries. Does nessie support presto queries?

Delta, iceberg, and hudi all support presto queries.

Thank you

**Comment by rymurr** [comment]
Hey @laopeng2021 welcome to the community!

Currently nessie doesn't support presto though it is very high up on the priority list. Since Nessie is supported in Iceberg as a custom catalog you may find that presto already supports nessie owned iceberg tables. Though we haven't tested yet.
