### ISSUE TITLE
about hudi

### ISSUE THREAD

**Issue by laopeng2021** [projectnessie/nessie#744]
Data Lake has 3 well-known tools, iceberg, delta, hudi, nessie currently supports iceberg, delta, but does not support hudi, hudi seems more popular.

Is there any plan to support hudi in the future? Or do not plan to support hudi in the future.
Thank you

**Comment by rymurr** [comment]
Hey @laopeng2021 There is a JIRA ticket open with Hudi: [HUDI-1455](https://issues.apache.org/jira/browse/HUDI-1455) so support is planned however we haven't gotten far on the implementation yet. Contributions welcome! :smile:
