### ISSUE TITLE
about nessie for dremio

### ISSUE THREAD

**Issue by laopeng2021** [projectnessie/nessie#745]
Dremio currently supports two data sources: data lake and external database. Will dremio use nessie as the third data source?

On the latest version of dremio, I haven't seen support for nessie yet. Do you have any plans?
Thank you

**Comment by rymurr** [comment]
Hey @laopeng2021 there are definitely plans in the works for Nessie supoport in Dremio. I can't yet comment on when or what that will look like. Stay tuned!

**Comment by laurentgo** [comment]
I would suggest to contact Dremio on their community page: https://community.dremio.com/

I'm closing this ticket as not relevant for Nessie
