### ISSUE TITLE
Nessie trying to connect to otlp endpoint when tracing is disabled

### ISSUE THREAD

**Issue by logicpeters** [projectnessie/nessie#7458]
I have Nessie (0.67.0( being deployed on a Kubernetes cluster in AWS (deployed via Helm).
Im trying to run basic commands from Trino to Nessie (via Trino CLI), such as 'show schemas' and 'create schema', and getting the following error from the Nessie logs:

    Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317

This (4317) looks like the otlp connector port, for the telemetry, however I have tracing disabled in the configuration:

    tracing:
      # -- Specifies whether tracing for the nessie server should be enabled.
      enabled: false

Everything in my configuration is set to the defaults.  Any ideas what is wrong?

**Comment by adutra** [comment]
Hi @logicpeters thanks for reporting this! The log message is benign in fact, but I agree that it's annoying. 

I usually get rid of this message by adding the following env var to `extraEnv`:

```yaml
    - name: QUARKUS_OTEL_SDK_DISABLED
      value: "true"
```

I wonder if we shouldn't include it automatically when `tracing.enabled` is false.

**Comment by logicpeters** [comment]
thanks!  this cleared the error message from the logs.  my actual problem turned out that I was using https instead of http in the connection URL
