### ISSUE TITLE
"Atomically" swapping a table through renames (e.g. with dbt through Trino) fails

### ISSUE THREAD

**Issue by marvin-roesch** [projectnessie/nessie#7492]
We're materializing dbt models as Iceberg tables backed by Nessie, going through Trino as query engine. When using the `table` materialization in dbt, i.e. creating the whole model from scratch every time the model gets materialized, dbt first creates a temporary table with the new contents and then attempts to "atomically" swap out the existing table by renaming it with a suffix and then renaming the temporary table to the original name.

This seems to cause trouble for Nessie.

**What happened**: When dbt runs the following queries:

```sql
ALTER TABLE iceberg.default.model RENAME TO iceberg.default.model__dbt_backup;
ALTER TABLE iceberg.default.model__dbt_tmp RENAME TO iceberg.default.model;
```

the second one fails with error message `New value for key 'default.model' must not have a content ID`. I can also reproduce this without going through Trino, see below.

**What you expected to happen**: The renames both should go through without issue.

**How to reproduce it (as minimally and precisely as possible)**:
Create two tables in the namespace `default` with names `model` and `model_tmp`, then run the following with `catalog` being a `NessieCatalog` from the Iceberg libraries:

```kotlin
catalog.renameTable(TableIdentifier.of("default", "model"), TableIdentifier.of("derived", "model_backup"))
catalog.renameTable(TableIdentifier.of("default", "model_tmp"), TableIdentifier.of("derived", "model"))
```

Observe that the second operation fails with the message `New value for key 'default.model' must not have a content ID`, while the first rename succeeds.

**Details**:
- Nessie server type (docker/built from source) and version: Docker v0.65.0 on Kubernetes
- Client type (Ex: UI/Spark/pynessie ...) and version: Trino 422 or Iceberg 1.3.1 Java libraries

**Comment by dimas-b** [comment]
What I posted above about atomicity holds.

`New value for key 'default.model' must not have a content ID` this error message may actually be a separate problem, because even if the related `ALTER TABLE` statements are not atomic as a pair, each of the renames should still be a rename, not a "new" table request.

@marvin-roesch : Would you be able to test `ALTER TABLE` with Trino in a simpler (sharable) use case?

**Comment by marvin-roesch** [comment]
@dimas-b I will try to produce a minimal test case with Trino. And indeed, the consecutive renames come from dbt which is in some sense agnostic to the underlying query engine and even more so to the underlying table format. So support for the atomic rename from within Trino would only have limited use to us anyway.

**Comment by snazy** [comment]
Hm - so the duplicate rename is definitely a bug in Nessie. Looking into it.

**Comment by snazy** [comment]
It might be though that whatever performs the `ALTER TABLE...RENAME` refers to the wrong (older) Nessie commit (without the table being renamed). In that case, Nessie validates the `Put` operation as a new table.

**Comment by snazy** [comment]
The Nessie catalog in Iceberg is fine though - verified with this test case in Iceberg/master and Iceberg 1.3.1:
```java
  @Test
  public void testMultipleRename() throws NessieNotFoundException {
    Table original = catalog.loadTable(TABLE_IDENTIFIER);

    TableIdentifier tableBackup =
        TableIdentifier.of(TABLE_IDENTIFIER.namespace(), "table_backup");
    TableIdentifier tableTmp =
        TableIdentifier.of(TABLE_IDENTIFIER.namespace(), "table_tmp");
    Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER);
    catalog.createTable(tableTmp, original.schema(), original.spec(), original.location(), original.properties());
    Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER, tableTmp);
    catalog.renameTable(TABLE_IDENTIFIER, tableBackup);
    Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(tableBackup, tableTmp);
    catalog.dropTable(tableBackup);
    Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(tableTmp);
    catalog.renameTable(tableTmp, TABLE_IDENTIFIER);
    Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER);
  }
```

Does dbt maybe use multiple Iceberg catalog instances?

**Comment by snazy** [comment]
Generally speaking, I think, such a use case would benefit from some `ALTER TABLE...REPLACE` - those CREATE/DROP/ALTER TABLE...RENAME` cascades are a bit ... strange.

**Comment by marvin-roesch** [comment]
I've now created a minimal example that reproduces the issue at [marvin-roesch/trino-nessie-repro](https://github.com/marvin-roesch/trino-nessie-repro). @snazy Your example seems to work due to dropping the backup table *before* renaming the temporary table to the original name. I've added that case to my example as well and that works fine as well. The order of operations for dbt is to first rename the tables and then drop the backup so the backup sticks around in case of any failure.

I was able to reproduce the issue with Iceberg/master adjusting the order of operations in your test case to perform the drop after the second rename. This is the test case:
```java
@Test
public void testMultipleRename() throws NessieNotFoundException {
  Table original = catalog.loadTable(TABLE_IDENTIFIER);

  TableIdentifier tableBackup =
          TableIdentifier.of(TABLE_IDENTIFIER.namespace(), "table_backup");
  TableIdentifier tableTmp =
          TableIdentifier.of(TABLE_IDENTIFIER.namespace(), "table_tmp");
  Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER);
  catalog.createTable(tableTmp, original.schema(), original.spec(), original.location(), original.properties());
  Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER, tableTmp);
  catalog.renameTable(TABLE_IDENTIFIER, tableBackup);
  Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(tableBackup, tableTmp);
  catalog.renameTable(tableTmp, TABLE_IDENTIFIER);
  Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER, tableBackup);
  catalog.dropTable(tableBackup);
  Assertions.assertThat(catalog.listTables(TABLE_IDENTIFIER.namespace())).containsExactlyInAnyOrder(TABLE_IDENTIFIER);
}
```

**Comment by snazy** [comment]
Duh! You're right. That let's Nessie fail.
I'll post a fix in a bit
