### ISSUE TITLE
Add table prefix option for DynamoDB

### ISSUE THREAD

**Issue by maxfirman** [projectnessie/nessie#7595]
**Description**:
Add a configuration option for the DynamoDB version store to add a prefix to all tables. 

There is a similar option available already for the BigTable as documented here: https://projectnessie.org/try/configuration/#bigtable-version-store-settings

**Requested Changes in public API**:
None

**Expected Use Cases**:
In many organisations it is common to map DynamoDB table permissions to individual teams/projects based on table prefix. This feature is therefore required for these organisations to use the DynamoDB backend.

**Comment by dimas-b** [comment]
@maxfirman : Do you feel like proposing a PR for this? :)

**Comment by maxfirman** [comment]
@dimas-b sure I'm happy to create a PR. I'll let you know once I've got something to review.
