### ISSUE TITLE
Examples in Nessie Docker Hub page are wrong

### ISSUE THREAD

**Issue by adutra** [projectnessie/nessie#7657]
**What happened**:

Examples shown in this page are wrong:

https://hub.docker.com/r/projectnessie/nessie

* Some lines are missing the continuation sign `\`
* The system properties should not be passed as `-Dname=value` but as `-e NAME=value`
* Config options should come before the docker image name

I cannot change that page myself and don't know who can. @dimas-b or @snazy maybe?

**Comment by snazy** [comment]
Fixed
