### ISSUE TITLE
Mismatch in optional fields in View serialization 

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#7752]
Dialect is nullable here.
https://github.com/projectnessie/nessie/blob/0e3191a82d7f48b3cafa62f76ab8506de89ba7e4/api/model/src/main/java/org/projectnessie/model/IcebergView.java#L58-L60

Dialect is not optional here
https://github.com/projectnessie/nessie/blob/0e3191a82d7f48b3cafa62f76ab8506de89ba7e4/servers/store-proto/src/main/proto/org/projectnessie/server/store/proto/table.proto#L104

So, we can't really set it null during commit operation.

**Comment by snazy** [comment]
Tackled by #8478
