### ISSUE TITLE
Nessie Iceberg Table support for Presto/Trino

### ISSUE THREAD

**Issue by laurentgo** [projectnessie/nessie#778]
Add support into Presto/Trino to read Iceberg Tables using Nessie

**Comment by rymurr** [comment]
Existing PR opened on Trino by AWS team. May have to follow up/help if a priority

**Comment by ajantha-bhat** [comment]
PR just got merged. (https://github.com/trinodb/trino/pull/11701)

The upcoming Trino 419 version will ship with the nessie support.

With Presto Nessie is already supported.
