### ISSUE TITLE
Grafana Dashboard: Some Panels show no data

### ISSUE THREAD

**Issue by tiwalter** [projectnessie/nessie#8032]
### Issue description

After the deployment of Nessie on Kubernetes and scraping the metrics with Prometheus, I imported the Grafana Dashboard (current version: nessie-0.76.6) of this repo. The following issues were identified:

## 1. VersionStore panels with no data

Here a screenshot of the `VersionStore` panels:

![grafik](https://github.com/projectnessie/nessie/assets/26794582/81fea676-d5c4-4455-b47e-e9addfb7cb81)

There are two root causes for this issue:

1. The label in the `nessie_versionstore_request_seconds_bucket` metric got changed. Instead of `request`, the label has the name `method`. In addition to that, we have to specify the `method` value as "lowerCamelCase".
2. The `nessie_databaseadapter_tryloop_duration_seconds_max` metric got removed (see: https://github.com/projectnessie/nessie/pull/6890)

## 2. "JVM Process Memory" panel with no data

Here A screenshot of the panel in editor mode:
![grafik](https://github.com/projectnessie/nessie/assets/26794582/c9a63fbb-430a-482f-8c38-0be2673c66ec)

The root causes for this issue are the missing metrics `process_memory_vss_bytes`, `process_memory_rss_bytes` and `process_memory_swap_bytes` in the metrics endpoint.

**Comment by tiwalter** [comment]
I created a PR that fixes this issue except the "JVM Process Memory panel with no data" problem. Maybe anyone of the community has a solution for the missing metrics. I also coudn't find equivalent metrics in the metrics endpoint.

If there is no solution, we could remove the "JVM Process Memory" panel.

**Comment by snazy** [comment]
Ah yea, this has probably never be checked again for a long while. Thanks for the PR!
I'll take a look.
