### ISSUE TITLE
[Feature]: Cluster mode deployment for Project Nessie

### ISSUE THREAD

**Issue by Ashwin07** [projectnessie/nessie#8085]
### Description

We are looking to implement a Data Lake house with Nessie as a table catalog, the important feature for us is to maintain this catalog in a high available environment, Does Nessie support cluster mode deployment and can it be implemented in high availability mode to support Disaster recovery?

**Comment by snazy** [comment]
This is rather a question for our [Zulip chat](https://project-nessie.zulipchat.com/). Please ask question there.
