### ISSUE TITLE
Would like to check if Nessie can store Iceberg metadata under GCS bucket

### ISSUE THREAD

**Issue by carillpower** [projectnessie/nessie#8130]
### Issue description

Currently building a trino integration with iceberg table, in order to make Iceberg table viewable in trino environment, I decided to use nessie as metastore. 

Currently I expect my Iceberg table to be stored in GCS bucket but when im using pyspark to create an Iceberg table with nessie as metadata. It throws an error like below

`Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"`

Turns out this was due to spark configuration I've made here
.set(f"spark.sql.catalog.{catalog_nm}.warehouse", GCS_WAREHOUSE)

I didnt found any reference using GCS as warehouse example, maybe I didnt research it in depth but if there is would be really helpful if anyone kind enough to share a link.

GCS = Google CLoud Storage

Thanks

**Comment by dimas-b** [comment]
Nessie is neutral to the table storage technology. It does not interpret Iceberg warehouse location URLs.

Nessie should work with any storage provide that is supported by Iceberg libraries.

**Comment by carillpower** [comment]
Understood.

Do you have some link I can refer if storing warehouse into GCS? as the error says otherwise

**Comment by dimas-b** [comment]
Sorry, I do not have any examples for that handy.

> Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"

With Hadoop, the URI scheme may have to be `gcs`, though.

**Comment by snazy** [comment]
This is not a Nessie issue, so closing this.
Feel free to chat more on https://project-nessie.zulipchat.com/
