### ISSUE TITLE
Artifact rename proposals for server and tooling

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#8245]
Rename proposals:
* Artifact `:nessie-quarkus` to `:nessie-server` (container image name stays as it is)
  * also update the quarkus-app-name to `nessie-server` (currently: `quarkus-app`)
* Artifact `:nessie-quarkus-cli` to `:nessie-server-admin`
  * also update the quarkus-app-name to `nessie-server-admin` (currently: `quarkus-app`)
* Artifact `:nessie-quarkus-tests` to `:nessie-server-tests`
* Artifact `:nessie-quarkus-common` to `:nessie-server-common`
* Artifact `:nessie-quarkus-auth` to `:nessie-server-auth`

(Ignoring CLI tools in this issue)

/cc @adutra @dimas-b

**Comment by snazy** [comment]
Thinking a bit more about this proposal, it's probably not good to implement this, because
a) a lot of documentation changes are needed
b) basically all downstream components (helm chart, k8s operator) would break
c) breaking changes for users

**Comment by adutra** [comment]
Sorry, but I disagree for `:nessie-quarkus-cli`: it's a bad name. I think we should tackle that part of the proposal.

**Comment by dimas-b** [comment]
`nessie-quarkus-cli` is a standalone tool. Renaming it should not have any downstream effects.

**Comment by dimas-b** [comment]
Not sure if we have a separate issue for that, but renaming the "content generator" tool might also be worth the trouble for the sake of clarify for end users.

**Comment by snazy** [comment]
I'm okay w/ renaming these two tools. Can you open issues or PRs?
