### ISSUE TITLE
re-set commit meta on transplant/merge

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#831]
Currently #818 only addresses adding properties to commit metadata. It does not correctly set them when rebasing or merging. This ticket is for the follow up task of setting commit meta on transplant and merge.

Specifically:
1) committer should change to current principal
2) commit time should change to current time
3) author should stay the same or be the original committer (if null)
4) author time should stay the same or be the original commit time (if null)
5) perhaps add an item in properties to record more info about the merge/transplant (eg original branch, was it a merge or transplant etc)

**Comment by snazy** [comment]
Overall, this seems doable by adding a "mapper `Function<ByteString, ByteString>`" to `org.projectnessie.versioned.persist.adapter.spi.AbstractDatabaseAdapter#copyCommits` which takes the source commit-meta and returns an updated commit-meta.

**Comment by harshm-dremio** [comment]
@snazy on the following statement - 
> perhaps add an item in properties to record more info about the merge/transplant (eg original branch, was it a merge or transplant etc)

Do we have any convention already?

**Comment by snazy** [comment]
> Do we have any convention already?

Nope, not really.
