### ISSUE TITLE
[Bug]: Nessie GC fails to handle Iceberg column names with quotes in S3

### ISSUE THREAD

**Issue by clintf1982** [projectnessie/nessie#8328]
### What happened
I created using spark and iceberg a table X with columns `"_id"`,`B`, `C`
partitioned by truncate(2000, `"_id"`)
When inserting data into the table, under the data folder of the table in S3, folders of this kind were created:
s3://bucket/folder/X_12c98633-5492-48b4-950f-ec23497db481/data/"_id"_trunc=0/
After running the GC tool, I received an exception:
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 63.
at java.base/java.net.URI.create(URI.java:906)
at org.projectnessie.gc.iceberg.IcebergContentToFiles.dataFileUri(IcebergContentToFiles.java:262)
at org.projectnessie.gc.iceberg.IcebergContentToFiles.lambda$allDataFiles$3(IcebergContentToFiles.java:158)

### How to reproduce it
1)
CREATE TABLE X (
    `"_id"` bigint NOT NULL COMMENT 'unique id',
    A big int,
    B big int)
partitioned by truncate(2000, `"_id"`)
2)
insert into X values (100, 1, 1)
3)
drop table X
4) 
Run the gc tool with gc option to leave only the the last commit.

### Nessie server type (docker/uber-jar/built from source) and version

Spark 3.4
Iceberg 1.3.0
Nessie 0.70.0

### Client type (Ex: UI/Spark/pynessie ...) and version
Spark 3.4 (When creating the table and writing the data) with Iceberg tables.
Ran the GC tool from command line.

**Comment by dimas-b** [comment]
Example S3 URL: `s3://EXAMPLE_BUCKET/t3_f1808b75-737b-418a-b808-68c00847a4ab/data/"_id"_trunc=0/00000-1-65449b51-b183-4cb5-ba16-9802425dab38-0-00001.parquet`

**Comment by dimas-b** [comment]
@clintf1982 : Do you really need quotes in the column name or was it a co-incidence perhaps?

**Comment by dimas-b** [comment]
I was able to reproduce with a simpler script (manually):

Spark SQL:
```

**Comment by clintf1982** [comment]
@dimas-b 
Yeah, yours is simpler. First off, i'm glad everything is clear and you successed to reproduce.
1. You are right, if we wouldn't have columns with quotes, there wouldn't be a problem, however, even if we changed now the columns and removed quotes, the history still has the quotes and the GC would fail(At least I think so), which makes us unable at all to clean the unused data/metadata at this point.
2. Since there wasn't a failure by nessie/iceberg/S3 to write such files, then the GC shouldn't fail on these files. I guess java.net.URI is not suitable for S3 although as far as I saw in the code java.net.URI is heavily used.

Thank you for time, it is appreciated. I will follow this issue to see how we should move forward.

**Comment by clintf1982** [comment]
@dimas-b It is a blocker for us, we have many tables with quoted columns and we can't GC our data.

**Comment by dimas-b** [comment]
Iceberg metadata (`GenericDataFile`) appears to store S3 URIs without escaping quotes :thinking:

**Comment by dimas-b** [comment]
@clintf1982 : This should be fixed in v. 0.81.0

**Comment by dimas-b** [comment]
@clintf1982 if you have `#` in column names, please do not use GC in 0.81.0... there seems to be another latent bug... we're investigating.

**Comment by dimas-b** [comment]
Related issue: https://github.com/apache/iceberg/issues/10279

**Comment by clintf1982** [comment]
@dimas-b Currently we don't use # or ?, so PR10283 doesn't stop us.
The work done here in GC 0.81.0 is very appreciated, I guess I will be able to check it on our data soon.
