### ISSUE TITLE
Nessie aware version of icebergs remove orphan files

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#855]
The `RemoveOrphanFiles` action in Iceberg does some general cleanup but is tied to a signle metadata file. This could be destructive if run under Nessie. The Nessie GC algo only locates 'formerly referenced' files but not unreferenced. This would require doing an `ls` of the metadata directory and comparing the resulting set of files to the set of referenced and unreferenced.

**Comment by rymurr** [comment]
We might also be able to get away with running icebergs `RemoveOrphanFiles` with a no-op deleter on all branches and combining the reuslts

**Comment by ajantha-bhat** [comment]
Tracked using https://github.com/projectnessie/nessie/issues/4694
