### ISSUE TITLE
[Feature]: Trino Iceberg view support for Nessie catalog

### ISSUE THREAD

**Issue by ajantha-bhat** [projectnessie/nessie#8574]
### Description

REST catalog has added the view support Trino side. 
https://github.com/trinodb/trino/pull/19818

There are users asking for view support for Trino Nessie catalog in Zulip and in Trino slack.

**Comment by ajantha-bhat** [comment]
I have done the analysis. 

`TrinoRestCatalog` directly uses `TrinoCatalog` and maintain `RestSessionCatalog` class from Iceberg repo. 

where as all other Iceberg catalogs (like Nessie) uses `AbstractTrinoCatalog`. 
So, we need to duplicate lot of code from `BaseMetastoreViewCatalog`? There is also `AbstractIcebergTableOperations` instead of directly using the class from Iceberg repo. That means we also need to introduce `AbstractIcebergViewOperations` for Trino? 

So, I estimate that this is a big work which involves lot of duplication. 

I see two simpler ways.
a) Make `TrinoNessieCatalog` like `TrinoRestCatalog` by directly using the `NessieCatalog` from Iceberg repo? Not sure why it was done in the first place. Need to understand it. 
b) Do nothing. Once, Nessie adopts rest catalog spec, the views can be created using the rest path. 

@nastra: WDYT?

**Comment by snazy** [comment]
Looks like this issue would better be opened in the Trino GH repo, no?
