### ISSUE TITLE
[Bug]: WARN  [org.pro.qua.pro.sto.AddressResolver] (vert.x-eventloop-thread-1) Failed to resolve 'nessiecatalog-mgmt' to A/AAAA records: io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error

### ISSUE THREAD

**Issue by sdasdasd1** [projectnessie/nessie#8829]
### What happened

In nessie logs see this
WARN  [org.pro.qua.pro.sto.AddressResolver] (vert.x-eventloop-thread-1) Failed to resolve 'nessiecatalog-mgmt' to A/AAAA records: io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error
Its spamming all time. Nessie was created from helm chart with standard settings

### How to reproduce it

Nessie was created from helm chart with standard settings
Just spamming this error in the logs

### Nessie server type (docker/uber-jar/built from source) and version

0.90.4

**Comment by snazy** [comment]
The `*-mgmt` is a generated for the Quarkus management service on port 9000 (not "externally" reachable) in [this file](https://github.com/projectnessie/nessie/blob/main/helm/nessie/templates/management-service.yaml). It is used to let all Nessie instances know the addresses of all (other) Nessie instances.

Can you provide a reproducer?

**Comment by sdasdasd1** [comment]
@snazy I can see that someone have same issue https://github.com/projectnessie/nessie/issues/8840
Also can it trigger my another issue https://github.com/projectnessie/nessie/issues/8830?

**Comment by tamarinkeisari** [comment]
Hi, did anyone find a solution? Or what causing the problem?

**Comment by snazy** [comment]
The problem is "just" that the service-name is provided without the DNS domain. I'll push a PR shortly.

**Comment by snazy** [comment]
> Also can it trigger my another issue #8830?

Nope
