### ISSUE TITLE
[Catalog] Request signing for GCS

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#8910]
The concept behind `com.google.cloud.storage.Storage.signUrl()` looks similar to S3 request signing.

To implement this one, a change in Iceberg is required.

**Comment by hangc0276** [comment]
I tested the Nessie GCS signing with Iceberg 1.5.2 client, it works.

**Comment by snazy** [comment]
@hangc0276 can you elaborate what you did? AFAIU Iceberg doesn't have a mechanism like S3 request signing yet.

**Comment by hangc0276** [comment]
> @hangc0276 can you elaborate what you did? AFAIU Iceberg doesn't have a mechanism like S3 request signing yet.

@snazy I configured the GCS SERVICE_ACCOUNT credential on the Nessie server and used the Iceberg java client to connect to Nessie Iceberg REST API and commit the iceberg snapshot, it works.

**Comment by snazy** [comment]
Yes, but that's not request signing (aka signing each storage access) :)

**Comment by hangc0276** [comment]
@snazy You are correct. My Iceberg Java client can write to the GCS bucket because my local gcloud account has write permission to the GCS bucket. We are watching for the signing of the GCS feature.

**Comment by snazy** [comment]
Closing in favor of #9298
