### ISSUE TITLE
[Bug]: files and all_data_files both data_files both returning only current snapshot data files

### ISSUE THREAD

**Issue by shraddhagrawal** [projectnessie/nessie#9125]
### What happened

I have executed data re-write https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_data_files procedure which created new data files and when I am querying data_files table or all_data_files for iceberg table its returning only newly created parquet data files.
As per iceberg documentation all_data_files should return all files including older files
i need these details for calculating metrics of size of current table / total size of data files

### How to reproduce it

1. Create table and insert few records
2. Execute rewrite data files which will create new data files
3. query all_data_Files and data_files 

### Nessie server type (docker/uber-jar/built from source) and version

docker

### Client type (Ex: UI/Spark/pynessie ...) and version

Spark

**Comment by snazy** [comment]
Nessie only returns the Iceberg snapshot for the current Nessie commit - this is a design choice.

See #8991 ([this comment](https://github.com/projectnessie/nessie/issues/8991#issuecomment-2203880883)), which is about the same question.

The [Iceberg docs mention](https://iceberg.apache.org/docs/latest/spark-queries/#files):
> To show all files, data files and delete files across all **tracked** snapshots

**Comment by shraddhagrawal** [comment]
@snazy Is there any way we can find all files for metrics in nessie

**Comment by dimas-b** [comment]
@shraddhagrawal : Please take a look at how Nessie [GC](https://github.com/projectnessie/nessie/tree/main/gc) finds Iceberg files.
