### ISSUE TITLE
[Bug]: GC - Iceberg views metadata is not getting deleted

### ISSUE THREAD

**Issue by shraddhagrawal** [projectnessie/nessie#9138]
### What happened

Iceberg views metadata is not getting deleted with Nessie gc 0.92.1

### How to reproduce it

1. Created iceberg view using `CREATE OR REPLACE VIEW nessie.demonamespace.test_view AS SELECT *  FROM nessie.demonamespace.demotable;`
2. Make few changes to test_view for 3-4 times
3. Execute mark live with default cut-off as 2 and execute expire command
4. Metadata files created in first commit should be deleted but its not getting deleted

### Nessie server type (docker/uber-jar/built from source) and version

docker

### Client type (Ex: UI/Spark/pynessie ...) and version

Spark

**Comment by snazy** [comment]
Thanks for the report. It is already handled via #9074
