### ISSUE TITLE
dremio blog post :  nessie , missing alternative

### ISSUE THREAD

**Issue by raphaelauv** [projectnessie/nessie#918]
Hi , It's not really an issue , but "discussions" is not activate on this repo.

Your blog post on nessie : https://www.dremio.com/subsurface/nessie-git-for-data-lakes

is missing the alternative opens source of nessie : lakeFS

You mention alternative at the "open table format", it would be nice to do the same for "table repositories"

disclamer : I'm not related to lakeFS

![nessie-table-repository](https://user-images.githubusercontent.com/10202690/110255067-408f0680-7f92-11eb-8d39-0992f1d79961.jpg)

Thank you all

**Comment by jacques-n** [comment]
While I agree that lakefs provides some similar features to Nessie, it does so in a very different way. In essence, I don't think of lakeFS as a table repository. Last I checked (I'm not a lakeFS expert), lakeFS has no awareness of table and file formats (whereas Nessie definitely does). I think of it more as an advanced object store with versioning (which delegates base object storage to traditional object stores). A table repo doesn't work with objects, it works with tables that have schema and move forward in time. One of the key requirements for a table repository is the ability to list what tables are in the system. Hive and AWS Glue provide this capability. lakefs (I believe), does not. So if I were to add lakefs to this chart, I would add it to the bottom tier next to S3 and ADLS (a very different level of abstraction).

**Comment by rymurr** [comment]
I agree with @jacques-n, in my opinion lakeFS and Nessie are trying to do different things and shouldn't be directly compared like that. However, it may be worth adding a similar technologies section to the docs at some point.

@raphaelauv to your comment on the 'discussions' section of the repo. We prefer to have discussions on the [mailing list](https://groups.google.com/g/projectnessie) or the [slack channel](mailto:slack-subscribe@projectnessie.org). Feel free to join either! Happy to answer questions and discuss more :-)
