### ISSUE TITLE
[Bug]: Nessie GC table properties override did not work 

### ISSUE THREAD

**Issue by shraddhagrawal** [projectnessie/nessie#9200]
### What happened

I have set table properties for iceberg tables 
```
history.expire.max-snapshot-age-ms = 518400000 
history.expire.min-snapshots-to-keep = 6
```
and if I execute gc with cut off policy as 2 then gc is not considering history.expire.min-snapshots-to-keep table property

### How to reproduce it

1. Create iceberg table and set table properties as mentioned above
2. Execute Nessie gc with default cutoff=2

### Nessie server type (docker/uber-jar/built from source) and version

docker

### Client type (Ex: UI/Spark/pynessie ...) and version

Spark

**Comment by snazy** [comment]
Nessie GC does not work this way, so this is not a bug. Please see the [docs here](https://projectnessie.org/nessie-latest/gc/).
If you have additional questions, please join our [Zulip chat](https://project-nessie.zulipchat.com/).
