### ISSUE TITLE
Support for pyiceberg using s3 signer

### ISSUE THREAD

**Issue by guitcastro** [projectnessie/nessie#9318]
### Issue description

It's not possible to use Nessie rest s3 signer with pyiceberg. This is on [their side](https://github.com/apache/iceberg-python/issues/1028), and I working to fix it. I am opening an issue here just to keep track.

**Comment by hienphdev** [comment]
Currently, there's a workaround to make pyiceberg works:
- apply the patch on main branch https://github.com/apache/iceberg-python/pull/1033
- pyiceberg _s3 reads remote sign by checking the key `s3.signer=S3V4RestSigner` (https://github.com/apache/iceberg-python/blob/main/pyiceberg/io/fsspec.py#L132-L146). So somehow nessie returns this key or pyiceberg performs another check likes 
```python
    if properties.get("s3.remote-signing-enabled", None):
        properties["s3.signer"] = "S3V4RestSigner"
    if signer := properties.get("s3.signer"):
```
And make sure you're using FsSpec
```python
catalog = load_catalog(
    "nessie",
    **{
        ...
        "py-io-impl": "pyiceberg.io.fsspec.FsspecFileIO",
    },
)
```

**Comment by hienduyph** [comment]
Currently, there's a workaround to make pyiceberg works:
- apply the patch on main branch https://github.com/apache/iceberg-python/pull/1033
- pyiceberg _s3 reads remote sign by checking the key `s3.signer=S3V4RestSigner` (https://github.com/apache/iceberg-python/blob/main/pyiceberg/io/fsspec.py#L132-L146). So somehow nessie returns this key or pyiceberg performs another check likes 
```python
    if properties.get("s3.remote-signing-enabled", None):
        properties["s3.signer"] = "S3V4RestSigner"
    if signer := properties.get("s3.signer"):
```
And make sure you're using FsSpec
```python
catalog = load_catalog(
    "nessie",
    **{
        ...
        "py-io-impl": "pyiceberg.io.fsspec.FsspecFileIO",
    },
)
```

**Comment by EternalDeiwos** [comment]
How exactly is this intended to be used? Signed requests worked fine using Spark without any explicit changes but attempting to do this with pyiceberg doesn't seem to work the same. I've not explicitly enabled or disabled anything related to request signing in the Nessie config.

`table.io.properties`

```
{
  ...
  "s3.remote-signing-enabled": "false",
  ...
}
```

When trying `table.scan()`: 

```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
