### ISSUE TITLE
Evaluate validation rules for legal branch and tag names.

### ISSUE THREAD

**Issue by jacques-n** [projectnessie/nessie#96]
I think we should probably adopt some naming rules for branches and tags. For hive, they only allow the following for database names: [a-zA-z_0-9]+

I'm not sure whether Git enforces this but it feels like it would best to keep things readable. (I'm not sure if that actually means constraining to latin but at least avoiding the null character seems like a good idea...)

**Comment by snazy** [comment]
Closing this in favor of #578 (just because it has more information)
(Sorry, haven't seen this when I opened 578)
