### ISSUE TITLE
[Bug]: Only last snapshot/operation presented in iceberg service tables

### ISSUE THREAD

**Issue by Albel-Analyst** [projectnessie/nessie#9634]
### What happened

I have a problem with nessie rest catalog
I dont have any snapshots in iceberg snapshot/history tables except last one

### How to reproduce it

Nessie k8s

image:
  tag: "0.95.0"

versionStoreType: JDBC (postgresql)
REST mode

Create any table and write some data in it for a several times in Spark or Trino like
```python
spark.sql("""
CREATE OR REPLACE TABLE iceberg_nessie.temp_db.test (
  _app_name_ STRING,
  _app_version_ STRING)
USING iceberg
TBLPROPERTIES (
  'commit.retry.num-retries' = '10',
  'format-version' = '2',
  'gc.enabled' = 'true',
  'write.distribution-mode' = 'hash',
  'write.format.default' = 'parquet',
  'write.metadata.previous-versions-max' = '100',
  'write.parquet.compression-codec' = 'ZSTD')
""").show()

import random
import datetime


data = [(
    "App_" + str(random.randint(1, 1000)),
    "1." + str(random.randint(0, 10)),
)]
columns = [
    '_app_name_',
    '_app_version_',
]

# Create a DataFrame with the random data
df = spark.createDataFrame(data, columns)

# Insert the DataFrame into the Iceberg table
df.writeTo("iceberg_nessie.temp_db.test").append()
df.writeTo("iceberg_nessie.temp_db.test").append()

spark.sql('select * from temp_db.test33.snapshots').show()
``` 
And you will see only one entry... 

### Nessie server type (docker/uber-jar/built from source) and version

0.95.0

### Client type (Ex: UI/Spark/pynessie ...) and version

Spark/Trino

**Comment by snazy** [comment]
It's intentional behaviour, see [here](https://projectnessie.org/guides/iceberg-rest/#time-travel-with-iceberg-rest)
