### ISSUE TITLE
Update python demo with icebergs next release

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#974]
Upon next iceberg release we have to:

* update reference to jar
* update `url` -> `uri`
* potentially add sql extensions etc depending on which Nessie PRs make it into Iceberg

We may also want to add an example of the GC algo in action

**Comment by snazy** [comment]
It's a bit difficult to "keep the dependencies in sync". At the moment we're working on 0.4.1-SNAPSHOT but reference Iceberg 0.11, which includes Nessie 0.3.0 in our Jupyter demo notebooks in "current master" rely on Nessie 0.3.0. It's confusing. :(
We should probably setup a separate repo for demos and all other stuff that's going to run against "proper releases" of Nessie, Iceberg, etc. that, at least within a self-contained demo, uses consistent versions.
Thoughts?

**Comment by snazy** [comment]
So far working: Nessie 0.5.1 against Iceberg 0.11.1 w/ Spark 3.0.
Also working: Upcoming Nessie 0.6 against upcoming Iceberg 0.12 w/ Spark 3.0 and Spark 3.1.

**Comment by snazy** [comment]
@rymurr can we close this one now?
