### ISSUE TITLE
[Feature]: Add feature to add additional initContainers in the Helm chart

### ISSUE THREAD

**Issue by goober** [projectnessie/nessie#9771]
### Description

We are running minio within the same Kubernetes cluster with a certificate signed with the internal Kubernetes CA. To be able to add the CA to the truststore we would need to run an initContainer for adding the kubernetes CA to the java trust store so Nessie doesn't complain on untrusted certificates when we are trying to connect to the minio bucket.

The proposed solution is to make it possible to configure an initContainer from the helm chart where the truststore can be created and mounted to main container.

I am willing to provide a PR if the feature is accepted

### Expected Use Cases

Add custom certificates to the trust store in an initContainer e.g. the internal Kubernetes CA

**Comment by snazy** [comment]
Sounds great!

> I am willing to provide a PR if the feature is accepted

Sure!

/cc @adutra
