### ISSUE TITLE
[Bug]: Nessie-gc deletes puffin files

### ISSUE THREAD

**Issue by krisisliss** [projectnessie/nessie#9879]
### What happened

Nessie-gc deletes puffin files which were created by trino

### How to reproduce it

1. Create new iceberg table
2. Run queries with trino
3. Table metadata path contains several .stats files
4. Run nessie-gc
5. All .stats files were deleted

### What I expect
Puffin files were not deleted

### Nessie server type (docker/uber-jar/built from source) and version

docker ghcr.io/projectnessie/nessie-gc:0.95.0

### Client type (Ex: UI/Spark/pynessie ...) and version

_nessie-tool cli_

**Comment by snazy** [comment]
(should be) fixed via ##9898
