### ISSUE TITLE
[Feature]: Helm — specify `externalTrafficPolicy` for service

### ISSUE THREAD

**Issue by EternalDeiwos** [projectnessie/nessie#9998]
### Description

I'd like my external load balancer to handle the load balancing.

### Expected Use Cases

Override the value for `externalTrafficPolicy` for the main and extra service definitions

### Requested Changes in public API

N/A

**Comment by adutra** [comment]
Hi! Would you have time to contribute a small PR?

**Comment by EternalDeiwos** [comment]
Sure; I'll make one for #10006 as well if you're happy with that?

I would offer to do #9997 but I am not sure how you'd want to handle it.
